import { FieldMetadataType } from 'twenty-shared/types';

import { type FieldMetadataSeed } from 'src/engine/workspace-manager/dev-seeder/metadata/types/field-metadata-seed.type';

export const TENANT_TICKET_DETAILS_FIELD_SEEDS: FieldMetadataSeed[] = [
  {
    type: FieldMetadataType.TEXT,
    label: 'Ticket Name',
    name: 'ticketName',
    icon: 'IconTag',
    isNullable: true,
  },
  {
    type: FieldMetadataType.TEXT,
    label: 'Conversation ID',
    name: 'conversationId',
    icon: 'IconMessage',
    description: 'External conversation/chat thread identifier',
    isNullable: true,
  },
  {
    type: FieldMetadataType.SELECT,
    label: 'Category Phase',
    name: 'categoryPhase',
    icon: 'IconTimeline',
    isNullable: true,
    options: [
      {
        label: 'Pre Move-In',
        value: 'PRE_MOVE_IN',
        position: 0,
        color: 'blue',
      },
      {
        label: 'Gestation',
        value: 'GESTATION',
        position: 1,
        color: 'orange',
      },
      { label: 'Active', value: 'ACTIVE', position: 2, color: 'green' },
    ],
  },
  {
    type: FieldMetadataType.DATE_TIME,
    label: 'Time Slot',
    name: 'timeSlot',
    icon: 'IconClock',
    description: 'Scheduled time slot for vendor visit or service',
    isNullable: true,
  },
  {
    type: FieldMetadataType.SELECT,
    label: 'Ticket Flag',
    name: 'ticketFlag',
    icon: 'IconFlag',
    description: 'Reasonableness assessment of the ticket request',
    isNullable: true,
    options: [
      {
        label: 'Reasonable',
        value: 'REASONABLE',
        position: 0,
        color: 'green',
      },
      {
        label: 'Not Reasonable',
        value: 'NOT_REASONABLE',
        position: 1,
        color: 'red',
      },
      {
        label: 'Subjective',
        value: 'SUBJECTIVE',
        position: 2,
        color: 'orange',
      },
    ],
  },
  {
    type: FieldMetadataType.RICH_TEXT,
    label: 'Flag Notes',
    name: 'flagNotes',
    icon: 'IconNotes',
    description: 'Explanation for the ticket flag assessment',
    isNullable: true,
  },
  {
    type: FieldMetadataType.CURRENCY,
    label: 'Cost Paid by Flent',
    name: 'costPaidByFlent',
    icon: 'IconCurrencyRupee',
    description: 'Amount paid by Flent for this ticket resolution',
    isNullable: true,
  },
  {
    type: FieldMetadataType.CURRENCY,
    label: 'Total Cost',
    name: 'totalCost',
    icon: 'IconCurrencyRupee',
    description:
      'Derived: costPaidByFlent minus amounts collected from tenant/merchant',
    isNullable: true,
  },
  {
    type: FieldMetadataType.TEXT,
    label: 'Vendor Group Chat ID',
    name: 'vendorGroupChatId',
    icon: 'IconMessages',
    description: 'WhatsApp or chat group ID for vendor coordination',
    isNullable: true,
  },
  {
    type: FieldMetadataType.TEXT,
    label: 'Related Tickets',
    name: 'relatedTickets',
    icon: 'IconLink',
    description: 'Comma-separated list of related ticket IDs',
    isNullable: true,
  },
  {
    type: FieldMetadataType.NUMBER,
    label: 'Time to First Rep Assignment',
    name: 'timeToFirstRepAssignment',
    icon: 'IconClockHour4',
    description: 'Minutes from ticket creation to first rep assignment',
    isNullable: true,
  },
  {
    type: FieldMetadataType.NUMBER,
    label: 'Time to First Response SLA (Hours)',
    name: 'timeToFirstResponseSlaHours',
    icon: 'IconClockHour8',
    description:
      'Hours from ticket creation to first customer-facing response',
    isNullable: true,
  },
  {
    type: FieldMetadataType.RATING,
    label: 'Tenant Rating',
    name: 'tenantRating',
    icon: 'IconStars',
    description: 'Tenant satisfaction rating (1-5)',
    isNullable: true,
    options: [
      { label: '1', value: 'RATING_1', position: 0 },
      { label: '2', value: 'RATING_2', position: 1 },
      { label: '3', value: 'RATING_3', position: 2 },
      { label: '4', value: 'RATING_4', position: 3 },
      { label: '5', value: 'RATING_5', position: 4 },
    ],
  },
  {
    type: FieldMetadataType.RICH_TEXT,
    label: 'CSAT Feedback',
    name: 'csatFeedback',
    icon: 'IconMessageReport',
    description: 'Customer satisfaction survey feedback text',
    isNullable: true,
  },
  {
    type: FieldMetadataType.RICH_TEXT,
    label: 'CSAT Response',
    name: 'csatResponse',
    icon: 'IconMessageCheck',
    description: 'Internal response/notes on CSAT feedback',
    isNullable: true,
  },
];
