apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: hawkeye-backend-config
  namespace: twenty-prod
  labels:
    app: hawkeye
    app.kubernetes.io/part-of: twenty
spec:
  healthCheck:
    checkIntervalSec: 15
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 3
    type: HTTP
    requestPath: /
    port: 3001
