import { FieldMetadataType } from 'twenty-shared/types';

import { type FieldMetadataSeed } from 'src/engine/workspace-manager/dev-seeder/metadata/types/field-metadata-seed.type';

export const TENANT_FIELD_SEEDS: FieldMetadataSeed[] = [
  {
    type: FieldMetadataType.FULL_NAME,
    name: 'name',
    label: 'Name',
    description: "Tenant's full name",
    icon: 'IconUser',
    isNullable: false,
  },
  {
    type: FieldMetadataType.EMAILS,
    name: 'emails',
    label: 'Email',
    description: "Tenant's email address",
    icon: 'IconMail',
    isNullable: false,
  },
  {
    type: FieldMetadataType.PHONES,
    name: 'phones',
    label: 'Phone',
    description: "Tenant's mobile and WhatsApp numbers",
    icon: 'IconPhone',
    isNullable: false,
  },
  {
    type: FieldMetadataType.SELECT,
    name: 'gender',
    label: 'Gender',
    description: "Tenant's gender",
    icon: 'IconGenderBigender',
    options: [
      { label: 'Male', value: 'MALE', position: 0, color: 'blue' },
      { label: 'Female', value: 'FEMALE', position: 1, color: 'pink' },
    ],
  },
  {
    type: FieldMetadataType.DATE,
    name: 'dateOfBirth',
    label: 'Date of Birth',
    description: "Tenant's date of birth",
    icon: 'IconCalendar',
    isNullable: true,
  },
  {
    type: FieldMetadataType.TEXT,
    name: 'aadhaarNumber',
    label: 'Aadhaar Number',
    description: "Tenant's Aadhaar ID number",
    icon: 'IconId',
    isNullable: false,
    defaultValue: "''",
  },
  {
    type: FieldMetadataType.LINKS,
    name: 'aadhaarFrontImage',
    label: 'Aadhaar Front Image',
    description: "URL to tenant's Aadhaar card front image",
    icon: 'IconPhoto',
    isNullable: true,
  },
  {
    type: FieldMetadataType.LINKS,
    name: 'aadhaarBackImage',
    label: 'Aadhaar Back Image',
    description: "URL to tenant's Aadhaar card back image",
    icon: 'IconPhoto',
    isNullable: true,
  },
  {
    type: FieldMetadataType.TEXT,
    name: 'pan',
    label: 'PAN',
    description: "Tenant's PAN number",
    icon: 'IconId',
    isNullable: false,
    defaultValue: "''",
  },
  {
    type: FieldMetadataType.LINKS,
    name: 'panCardImage',
    label: 'PAN Card Image',
    description: "URL to tenant's PAN card image",
    icon: 'IconPhoto',
    isNullable: true,
  },
  {
    type: FieldMetadataType.LINKS,
    name: 'linkedinUrl',
    label: 'LinkedIn',
    description: "Tenant's LinkedIn profile URL",
    icon: 'IconBrandLinkedin',
    isNullable: true,
  },
  {
    type: FieldMetadataType.LINKS,
    name: 'twitterUrl',
    label: 'Twitter',
    description: "Tenant's Twitter profile URL",
    icon: 'IconBrandTwitter',
    isNullable: true,
  },
  {
    type: FieldMetadataType.TEXT,
    name: 'instagramId',
    label: 'Instagram ID',
    description: "Tenant's Instagram handle",
    icon: 'IconBrandInstagram',
    isNullable: true,
    defaultValue: "''",
  },
  {
    type: FieldMetadataType.TEXT,
    name: 'occupation',
    label: 'Occupation',
    description: "Tenant's current occupation",
    icon: 'IconBriefcase',
    isNullable: true,
    defaultValue: "''",
  },
  {
    type: FieldMetadataType.TEXT,
    name: 'employerName',
    label: 'Employer Name',
    description: "Tenant's employer name",
    icon: 'IconBuilding',
    isNullable: true,
    defaultValue: "''",
  },
  {
    type: FieldMetadataType.SELECT,
    name: 'tenantLifecycle',
    label: 'Lifecycle Stage',
    description: "Tenant's current lifecycle stage - SINGLE SOURCE OF TRUTH",
    icon: 'IconTimeline',
    options: [
      { label: 'New Inquiry', value: 'NEW_INQUIRY', position: 0, color: 'sky' },
      { label: 'Visit Scheduled', value: 'VISIT_SCHEDULED', position: 1, color: 'blue' },
      { label: 'Visit Done', value: 'VISIT_DONE', position: 2, color: 'turquoise' },
      { label: 'Negotiation', value: 'NEGOTIATION', position: 3, color: 'yellow' },
      { label: 'Converted', value: 'CONVERTED', position: 4, color: 'green' },
      { label: 'Gestation', value: 'GESTATION', position: 5, color: 'purple' },
      { label: 'Moved In', value: 'MOVED_IN', position: 6, color: 'green' },
      { label: 'Notice Period', value: 'NOTICE_PERIOD', position: 7, color: 'orange' },
      { label: 'Moved Out', value: 'MOVED_OUT', position: 8, color: 'red' },
      { label: 'Dead Lead', value: 'DEAD_LEAD', position: 9, color: 'red' },
    ],
  },
];
