import { FieldMetadataType } from 'twenty-shared/types';

import { type FieldMetadataSeed } from 'src/engine/workspace-manager/dev-seeder/metadata/types/field-metadata-seed.type';

export const TENANT_ATTRIBUTION_FIELD_SEEDS: FieldMetadataSeed[] = [
  {
    type: FieldMetadataType.DATE_TIME,
    name: 'createDate',
    label: 'Create Date',
    description: 'Date the tenant record was first created',
    icon: 'IconCalendar',
    isNullable: true,
  },
  {
    type: FieldMetadataType.SELECT,
    name: 'firstInquiryChannel',
    label: 'First Inquiry Channel',
    description: 'Channel through which the tenant first made contact',
    icon: 'IconBrandWhatsapp',
    options: [
      { label: 'WhatsApp', value: 'WHATSAPP', position: 0, color: 'green' },
      { label: 'Website', value: 'WEBSITE', position: 1, color: 'blue' },
      { label: 'Instagram', value: 'INSTAGRAM', position: 2, color: 'purple' },
      { label: 'Facebook', value: 'FACEBOOK', position: 3, color: 'blue' },
      { label: 'Direct Call', value: 'DIRECT_CALL', position: 4, color: 'sky' },
      { label: 'Walk-in', value: 'WALK_IN', position: 5, color: 'turquoise' },
      { label: 'Platform', value: 'PLATFORM', position: 6, color: 'yellow' },
      { label: 'Referral', value: 'REFERRAL', position: 7, color: 'orange' },
      { label: 'Offline Activation', value: 'OFFLINE_ACTIVATION', position: 8, color: 'red' },
      { label: 'LinkedIn', value: 'LINKEDIN', position: 9, color: 'blue' },
    ],
  },
  {
    type: FieldMetadataType.SELECT,
    name: 'sourceDrilldown1',
    label: 'Source Drilldown 1',
    description: 'Primary source drilldown for attribution',
    icon: 'IconSearch',
    options: [
      { label: 'Google Ads', value: 'GOOGLE_ADS', position: 0, color: 'blue' },
      { label: 'Meta Ads', value: 'META_ADS', position: 1, color: 'blue' },
      { label: 'Instagram Ads', value: 'INSTAGRAM_ADS', position: 2, color: 'purple' },
      { label: 'YouTube Ads', value: 'YOUTUBE_ADS', position: 3, color: 'red' },
      { label: 'Housing.com', value: 'HOUSING_COM', position: 4, color: 'orange' },
      { label: 'MagicBricks', value: 'MAGICBRICKS', position: 5, color: 'red' },
      { label: 'NoBroker', value: 'NOBROKER', position: 6, color: 'green' },
      { label: '99acres', value: 'NINETY_NINE_ACRES', position: 7, color: 'yellow' },
      { label: 'WhatsApp Organic', value: 'WHATSAPP_ORGANIC', position: 8, color: 'green' },
      { label: 'Walk-in', value: 'WALK_IN', position: 9, color: 'turquoise' },
      { label: 'Referral', value: 'REFERRAL', position: 10, color: 'orange' },
      { label: 'Direct Call', value: 'DIRECT_CALL', position: 11, color: 'sky' },
      { label: 'Other', value: 'OTHER', position: 12, color: 'red' },
    ],
  },
  {
    type: FieldMetadataType.TEXT,
    name: 'sourceDrilldown2',
    label: 'Source Drilldown 2',
    description: 'Secondary source drilldown detail',
    icon: 'IconSearch',
    isNullable: true,
    defaultValue: "''",
  },
  {
    type: FieldMetadataType.TEXT,
    name: 'waxCode',
    label: 'WAX Code',
    description: 'WhatsApp business code for tracking',
    icon: 'IconCode',
    isNullable: true,
    defaultValue: "''",
  },
  {
    type: FieldMetadataType.TEXT,
    name: 'googleClickId',
    label: 'Google Click ID',
    description: 'GCLID from Google Ads tracking',
    icon: 'IconBrandGoogle',
    isNullable: true,
    defaultValue: "''",
  },
  {
    type: FieldMetadataType.TEXT,
    name: 'facebookClickId',
    label: 'Facebook Click ID',
    description: 'FBCLID from Facebook Ads tracking',
    icon: 'IconBrandFacebook',
    isNullable: true,
    defaultValue: "''",
  },
  {
    type: FieldMetadataType.TEXT,
    name: 'utmSource',
    label: 'UTM Source',
    description: 'UTM source parameter',
    icon: 'IconLink',
    isNullable: true,
    defaultValue: "''",
  },
  {
    type: FieldMetadataType.TEXT,
    name: 'utmMedium',
    label: 'UTM Medium',
    description: 'UTM medium parameter',
    icon: 'IconLink',
    isNullable: true,
    defaultValue: "''",
  },
  {
    type: FieldMetadataType.TEXT,
    name: 'utmCampaign',
    label: 'UTM Campaign',
    description: 'UTM campaign parameter',
    icon: 'IconLink',
    isNullable: true,
    defaultValue: "''",
  },
  {
    type: FieldMetadataType.TEXT,
    name: 'utmContent',
    label: 'UTM Content',
    description: 'UTM content parameter',
    icon: 'IconLink',
    isNullable: true,
    defaultValue: "''",
  },
  {
    type: FieldMetadataType.TEXT,
    name: 'utmTerm',
    label: 'UTM Term',
    description: 'UTM term parameter',
    icon: 'IconLink',
    isNullable: true,
    defaultValue: "''",
  },
];
