apiVersion: v1
kind: Service
metadata:
  name: twenty-server
  namespace: twenty-prod
  labels:
    app: twenty-server
    app.kubernetes.io/part-of: twenty
    app.kubernetes.io/component: server
spec:
  type: ClusterIP
  selector:
    app: twenty-server
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
