import { FieldMetadataType } from 'twenty-shared/types';

import { type FieldMetadataSeed } from 'src/engine/workspace-manager/dev-seeder/metadata/types/field-metadata-seed.type';

export const FSIN_FIELD_SEEDS: FieldMetadataSeed[] = [
  {
    type: FieldMetadataType.TEXT,
    label: 'FSIN Code',
    name: 'fsinCode',
    icon: 'IconBarcode',
    description: 'Unique Furniture Standard Identification Number',
    isNullable: false,
    isUnique: true,
  },
  {
    type: FieldMetadataType.TEXT,
    label: 'Item Name',
    name: 'itemName',
    icon: 'IconTag',
    description: 'Human-readable product name',
    isNullable: false,
  },
  {
    type: FieldMetadataType.SELECT,
    label: 'Category',
    name: 'category',
    icon: 'IconCategory',
    description: 'Furniture category classification',
    isNullable: false,
    options: [
      { label: 'Bed', value: 'BED', position: 0, color: 'blue' },
      { label: 'Mattress', value: 'MATTRESS', position: 1, color: 'purple' },
      { label: 'Wardrobe', value: 'WARDROBE', position: 2, color: 'green' },
      {
        label: 'Study Table',
        value: 'STUDY_TABLE',
        position: 3,
        color: 'orange',
      },
      {
        label: 'Study Chair',
        value: 'STUDY_CHAIR',
        position: 4,
        color: 'yellow',
      },
      {
        label: 'Dining Table',
        value: 'DINING_TABLE',
        position: 5,
        color: 'turquoise',
      },
      {
        label: 'Dining Chair',
        value: 'DINING_CHAIR',
        position: 6,
        color: 'sky',
      },
      { label: 'Sofa', value: 'SOFA', position: 7, color: 'pink' },
      {
        label: 'Center Table',
        value: 'CENTER_TABLE',
        position: 8,
        color: 'red',
      },
      { label: 'TV Unit', value: 'TV_UNIT', position: 9, color: 'gray' },
      {
        label: 'Shoe Rack',
        value: 'SHOE_RACK',
        position: 10,
        color: 'blue',
      },
      {
        label: 'Bookshelf',
        value: 'BOOKSHELF',
        position: 11,
        color: 'purple',
      },
      { label: 'Curtain', value: 'CURTAIN', position: 12, color: 'green' },
      { label: 'Mirror', value: 'MIRROR', position: 13, color: 'orange' },
      {
        label: 'Appliance',
        value: 'APPLIANCE',
        position: 14,
        color: 'yellow',
      },
      {
        label: 'Kitchenware',
        value: 'KITCHENWARE',
        position: 15,
        color: 'turquoise',
      },
      { label: 'Bedding', value: 'BEDDING', position: 16, color: 'sky' },
      { label: 'Decor', value: 'DECOR', position: 17, color: 'pink' },
      { label: 'Storage', value: 'STORAGE', position: 18, color: 'red' },
      { label: 'Other', value: 'OTHER', position: 19, color: 'gray' },
    ],
  },
  {
    type: FieldMetadataType.SELECT,
    label: 'Unit of Measurement',
    name: 'uom',
    icon: 'IconRuler',
    description: 'Unit of measurement for inventory counting',
    isNullable: false,
    options: [
      { label: 'Piece', value: 'PIECE', position: 0, color: 'blue' },
      { label: 'Set', value: 'SET', position: 1, color: 'green' },
      { label: 'Pair', value: 'PAIR', position: 2, color: 'purple' },
      { label: 'Meter', value: 'METER', position: 3, color: 'orange' },
      { label: 'Kg', value: 'KG', position: 4, color: 'yellow' },
      { label: 'Box', value: 'BOX', position: 5, color: 'turquoise' },
      { label: 'Roll', value: 'ROLL', position: 6, color: 'sky' },
      { label: 'Bundle', value: 'BUNDLE', position: 7, color: 'pink' },
    ],
  },
  {
    type: FieldMetadataType.LINKS,
    label: 'Image',
    name: 'image',
    icon: 'IconPhoto',
    description: 'Product reference image URL',
    isNullable: true,
  },
  {
    type: FieldMetadataType.NUMBER,
    label: 'Reorder Point',
    name: 'reorderPoint',
    icon: 'IconAlertTriangle',
    description: 'Minimum stock level that triggers reorder',
    isNullable: true,
  },
  {
    type: FieldMetadataType.CURRENCY,
    label: 'Annual Depreciation',
    name: 'annualDepreciation',
    icon: 'IconTrendingDown',
    description: 'Yearly depreciation amount for accounting',
    isNullable: true,
  },
  {
    type: FieldMetadataType.CURRENCY,
    label: 'Perceived Value',
    name: 'perceivedValue',
    icon: 'IconCurrencyRupee',
    description: 'Current market/perceived value of the item type',
    isNullable: true,
  },
  {
    type: FieldMetadataType.SELECT,
    label: 'Packaging',
    name: 'packaging',
    icon: 'IconPackage',
    description: 'How the item is delivered',
    isNullable: true,
    options: [
      { label: 'Flatpack', value: 'FLATPACK', position: 0, color: 'blue' },
      { label: 'Assembled', value: 'ASSEMBLED', position: 1, color: 'green' },
    ],
  },
  {
    type: FieldMetadataType.NUMBER,
    label: 'Lego',
    name: 'lego',
    icon: 'IconPuzzle',
    description: 'Number of Lego (assembly complexity) units',
    isNullable: true,
  },
  {
    type: FieldMetadataType.SELECT,
    label: 'Status',
    name: 'status',
    icon: 'IconStatusChange',
    isNullable: false,
    defaultValue: "'ACTIVE'",
    options: [
      { label: 'Active', value: 'ACTIVE', position: 0, color: 'green' },
      {
        label: 'Discontinued',
        value: 'DISCONTINUED',
        position: 1,
        color: 'red',
      },
      { label: 'Draft', value: 'DRAFT', position: 2, color: 'gray' },
    ],
  },
];
