import { FieldMetadataType, NumberDataType } from 'twenty-shared/types';

import { type FieldMetadataDTO } from 'src/engine/metadata-modules/field-metadata/dtos/field-metadata.dto';
import { type FieldMetadataSeed } from 'src/engine/workspace-manager/dev-seeder/metadata/types/field-metadata-seed.type';

export const PROPERTY_LEAD_STAGE_FIELD_SEEDS: FieldMetadataSeed[] = [
  {
    type: FieldMetadataType.TEXT,
    name: 'ppid',
    label: 'PPID',
    description: 'Prospective property identifier (unique)',
    icon: 'IconHash',
    isNullable: true,
    isUnique: true,
    defaultValue: "''",
  },
  {
    type: FieldMetadataType.DATE_TIME,
    name: 'dateAdded',
    label: 'Date Added',
    description: 'Date the property lead was added to the pipeline',
    icon: 'IconCalendar',
    isNullable: true,
  },
  {
    type: FieldMetadataType.NUMBER,
    name: 'unitsCount',
    label: 'Units Count',
    description: 'Number of units in the property',
    icon: 'IconHash',
    isNullable: true,
    settings: {
      dataType: NumberDataType.INT,
      type: 'number',
    },
  } as FieldMetadataDTO<FieldMetadataType.NUMBER>,
  {
    type: FieldMetadataType.SELECT,
    name: 'dealType',
    label: 'Deal Type',
    description: 'Type of deal (residence vs enterprise)',
    icon: 'IconCategory',
    options: [
      { label: 'Residence Lead', value: 'RESIDENCE_LEAD', position: 0, color: 'blue' },
      { label: 'Enterprise Lead', value: 'ENTERPRISE_LEAD', position: 1, color: 'purple' },
    ],
  },
  {
    type: FieldMetadataType.NUMBER,
    name: 'apartmentCount',
    label: 'Apartment Count',
    description: 'Number of apartments in the property',
    icon: 'IconHash',
    isNullable: true,
    settings: {
      dataType: NumberDataType.INT,
      type: 'number',
    },
  } as FieldMetadataDTO<FieldMetadataType.NUMBER>,
  {
    type: FieldMetadataType.SELECT,
    name: 'propertyTypeLead',
    label: 'Property Type (Lead)',
    description: 'Property type as captured during lead stage',
    icon: 'IconHome',
    options: [
      { label: 'Apartment', value: 'APARTMENT', position: 0, color: 'blue' },
      { label: 'Villa', value: 'VILLA', position: 1, color: 'green' },
      { label: 'Independent House', value: 'INDEPENDENT_HOUSE', position: 2, color: 'purple' },
      { label: 'Row House', value: 'ROW_HOUSE', position: 3, color: 'turquoise' },
      { label: 'Penthouse', value: 'PENTHOUSE', position: 4, color: 'orange' },
      { label: 'Studio', value: 'STUDIO', position: 5, color: 'sky' },
    ],
  },
  {
    type: FieldMetadataType.SELECT,
    name: 'furnishingLead',
    label: 'Furnishing (Lead)',
    description: 'Furnishing status as captured during lead stage',
    icon: 'IconArmchair',
    options: [
      { label: 'Unfurnished', value: 'UNFURNISHED', position: 0, color: 'red' },
      { label: 'Semi-Furnished', value: 'SEMI_FURNISHED', position: 1, color: 'yellow' },
      { label: 'Partially Furnished', value: 'PARTIALLY_FURNISHED', position: 2, color: 'orange' },
      { label: 'Fully Furnished', value: 'FULLY_FURNISHED', position: 3, color: 'green' },
    ],
  },
  {
    type: FieldMetadataType.CURRENCY,
    name: 'expectedRent',
    label: 'Expected Rent',
    description: 'Expected monthly rent for the property',
    icon: 'IconCurrencyRupee',
    isNullable: true,
  },
  {
    type: FieldMetadataType.LINKS,
    name: 'googleMapLocationLead',
    label: 'Google Map Location',
    description: 'Google Maps URL for the property location',
    icon: 'IconMapPin',
    isNullable: true,
  },
  {
    type: FieldMetadataType.SELECT,
    name: 'dealStage',
    label: 'Deal Stage',
    description: 'Current stage in the deal pipeline',
    icon: 'IconTimeline',
    options: [
      { label: 'To be contacted', value: 'TO_BE_CONTACTED', position: 0, color: 'sky' },
      { label: 'In touch', value: 'IN_TOUCH', position: 1, color: 'blue' },
      { label: 'LL Interested', value: 'LL_INTERESTED', position: 2, color: 'turquoise' },
      { label: 'Qualified', value: 'QUALIFIED', position: 3, color: 'green' },
      { label: 'Evaluation', value: 'EVALUATION', position: 4, color: 'yellow' },
      { label: 'Negotiations', value: 'NEGOTIATIONS', position: 5, color: 'orange' },
      { label: 'Offer Extended', value: 'OFFER_EXTENDED', position: 6, color: 'purple' },
      { label: 'Under Contract', value: 'UNDER_CONTRACT', position: 7, color: 'green' },
      { label: 'To nurture', value: 'TO_NURTURE', position: 8, color: 'red' },
    ],
  },
  {
    type: FieldMetadataType.SELECT,
    name: 'disqualificationReason',
    label: 'Disqualification Reason',
    description: 'Reason the property lead was disqualified',
    icon: 'IconAlertCircle',
    options: [
      { label: 'Price Mismatch', value: 'PRICE_MISMATCH', position: 0, color: 'yellow' },
      { label: 'Location', value: 'LOCATION', position: 1, color: 'blue' },
      { label: 'Property Condition', value: 'PROPERTY_CONDITION', position: 2, color: 'orange' },
      { label: 'Regulatory', value: 'REGULATORY', position: 3, color: 'purple' },
      { label: 'Landlord Unresponsive', value: 'LANDLORD_UNRESPONSIVE', position: 4, color: 'red' },
      { label: 'Other', value: 'OTHER', position: 5, color: 'sky' },
    ],
  },
  {
    type: FieldMetadataType.SELECT,
    name: 'lostReason',
    label: 'Lost Reason',
    description: 'Reason the property deal was lost',
    icon: 'IconThumbDown',
    options: [
      { label: 'Chose Competitor', value: 'CHOSE_COMPETITOR', position: 0, color: 'red' },
      { label: 'Price', value: 'PRICE', position: 1, color: 'yellow' },
      { label: 'Timing', value: 'TIMING', position: 2, color: 'orange' },
      { label: 'Not Interested', value: 'NOT_INTERESTED', position: 3, color: 'red' },
      { label: 'Other', value: 'OTHER', position: 4, color: 'sky' },
    ],
  },
  {
    type: FieldMetadataType.NUMBER,
    name: 'exploratoryVisitScore',
    label: 'Exploratory Visit Score',
    description: 'Score from the exploratory property visit',
    icon: 'IconStar',
    isNullable: true,
    settings: {
      dataType: NumberDataType.INT,
      type: 'number',
    },
  } as FieldMetadataDTO<FieldMetadataType.NUMBER>,
  {
    type: FieldMetadataType.LINKS,
    name: 'potentialReport',
    label: 'Potential Report',
    description: 'Link to the property potential assessment report',
    icon: 'IconFile',
    isNullable: true,
  },
];
