import { FieldMetadataType, NumberDataType } from 'twenty-shared/types';

import { type FieldMetadataDTO } from 'src/engine/metadata-modules/field-metadata/dtos/field-metadata.dto';
import { type FieldMetadataSeed } from 'src/engine/workspace-manager/dev-seeder/metadata/types/field-metadata-seed.type';

export const PROPERTY_ACTIVE_FIELD_SEEDS: FieldMetadataSeed[] = [
  // --- Location & Identity ---
  {
    type: FieldMetadataType.TEXT,
    name: 'houseNo',
    label: 'House No',
    description: 'House or flat number',
    icon: 'IconHash',
    isNullable: true,
    defaultValue: "''",
  },
  {
    type: FieldMetadataType.NUMBER,
    name: 'activeUnitsCount',
    label: 'Active Units Count',
    description: 'Number of active units in this property',
    icon: 'IconHash',
    isNullable: true,
    settings: {
      dataType: NumberDataType.INT,
      type: 'number',
    },
  } as FieldMetadataDTO<FieldMetadataType.NUMBER>,
  {
    type: FieldMetadataType.TEXT,
    name: 'tier',
    label: 'Tier',
    description: 'Property tier classification',
    icon: 'IconStar',
    isNullable: true,
    defaultValue: "''",
  },
  {
    type: FieldMetadataType.TEXT,
    name: 'floor',
    label: 'Floor',
    description: 'Floor number or description',
    icon: 'IconStairs',
    isNullable: true,
    defaultValue: "''",
  },
  {
    type: FieldMetadataType.LINKS,
    name: 'googleMapLocation',
    label: 'Google Map Location',
    description: 'Google Maps URL for the active property',
    icon: 'IconMapPin',
    isNullable: true,
  },
  {
    type: FieldMetadataType.ADDRESS,
    name: 'address',
    label: 'Address',
    description: 'Full address of the property',
    icon: 'IconMapPin',
    isNullable: true,
  },
  {
    type: FieldMetadataType.TEXT,
    name: 'buildingSociety',
    label: 'Building / Society',
    description: 'Name of the building or housing society',
    icon: 'IconBuildingCommunity',
    isNullable: true,
    defaultValue: "''",
  },
  {
    type: FieldMetadataType.SELECT,
    name: 'activeCluster',
    label: 'Active Cluster',
    description: 'Cluster assignment for the active property',
    icon: 'IconMapPin',
    options: [
      { label: 'HSR', value: 'HSR', position: 0, color: 'blue' },
      { label: 'KRM', value: 'KRM', position: 1, color: 'green' },
      { label: 'IDR', value: 'IDR', position: 2, color: 'purple' },
      { label: 'MHD', value: 'MHD', position: 3, color: 'orange' },
      { label: 'BLD', value: 'BLD', position: 4, color: 'sky' },
      { label: 'MGR', value: 'MGR', position: 5, color: 'turquoise' },
      { label: 'HBL', value: 'HBL', position: 6, color: 'yellow' },
      { label: 'WHF', value: 'WHF', position: 7, color: 'red' },
    ],
  },

  // --- Amenities ---
  {
    type: FieldMetadataType.MULTI_SELECT,
    name: 'parkingType',
    label: 'Parking Type',
    description: 'Types of parking available',
    icon: 'IconCar',
    options: [
      { label: 'Covered', value: 'COVERED', position: 0, color: 'green' },
      { label: 'Open', value: 'OPEN', position: 1, color: 'blue' },
      { label: 'Basement', value: 'BASEMENT', position: 2, color: 'purple' },
      { label: 'None', value: 'NONE', position: 3, color: 'red' },
    ],
  },
  {
    type: FieldMetadataType.TEXT,
    name: 'parkingNumber',
    label: 'Parking Number',
    description: 'Assigned parking spot number',
    icon: 'IconHash',
    isNullable: true,
    defaultValue: "''",
  },
  {
    type: FieldMetadataType.SELECT,
    name: 'powerBackup',
    label: 'Power Backup',
    description: 'Power backup availability',
    icon: 'IconBolt',
    options: [
      { label: 'Full', value: 'FULL', position: 0, color: 'green' },
      { label: 'Partial', value: 'PARTIAL', position: 1, color: 'yellow' },
      { label: 'None', value: 'NONE', position: 2, color: 'red' },
    ],
  },
  {
    type: FieldMetadataType.MULTI_SELECT,
    name: 'waterSource',
    label: 'Water Source',
    description: 'Available water sources',
    icon: 'IconDroplet',
    options: [
      { label: 'Corporation', value: 'CORPORATION', position: 0, color: 'blue' },
      { label: 'Borewell', value: 'BOREWELL', position: 1, color: 'green' },
      { label: 'Tanker', value: 'TANKER', position: 2, color: 'yellow' },
    ],
  },
  {
    type: FieldMetadataType.SELECT,
    name: 'restrictions',
    label: 'Restrictions',
    description: 'Any restrictions on the property',
    icon: 'IconAlertCircle',
    options: [
      { label: 'None', value: 'NONE', position: 0, color: 'green' },
      { label: 'No Pets', value: 'NO_PETS', position: 1, color: 'yellow' },
      { label: 'No Smoking', value: 'NO_SMOKING', position: 2, color: 'orange' },
      { label: 'Veg Only', value: 'VEG_ONLY', position: 3, color: 'red' },
      { label: 'Male Only', value: 'MALE_ONLY', position: 4, color: 'blue' },
      { label: 'Female Only', value: 'FEMALE_ONLY', position: 5, color: 'pink' },
    ],
  },
  {
    type: FieldMetadataType.RICH_TEXT,
    name: 'otherNotes',
    label: 'Other Notes',
    description: 'Additional notes about the property',
    icon: 'IconNote',
    isNullable: true,
  },

  // --- Furnishing ---
  {
    type: FieldMetadataType.SELECT,
    name: 'furnitureMovement',
    label: 'Furniture Movement',
    description: 'Whether furniture can be moved in/out',
    icon: 'IconArmchair',
    options: [
      { label: 'Allowed', value: 'ALLOWED', position: 0, color: 'green' },
      { label: 'Not Allowed', value: 'NOT_ALLOWED', position: 1, color: 'red' },
      { label: 'With Permission', value: 'WITH_PERMISSION', position: 2, color: 'yellow' },
    ],
  },
  {
    type: FieldMetadataType.SELECT,
    name: 'furnishingStatus',
    label: 'Furnishing Status',
    description: 'Current furnishing level of the property',
    icon: 'IconArmchair',
    options: [
      { label: 'Unfurnished', value: 'UNFURNISHED', position: 0, color: 'red' },
      { label: 'Semi-Furnished', value: 'SEMI_FURNISHED', position: 1, color: 'yellow' },
      { label: 'Partially Furnished', value: 'PARTIALLY_FURNISHED', position: 2, color: 'orange' },
      { label: 'Fully Furnished', value: 'FULLY_FURNISHED', position: 3, color: 'green' },
    ],
  },

  // --- Financials ---
  {
    type: FieldMetadataType.CURRENCY,
    name: 'finalApprovedAmt',
    label: 'Final Approved Amount',
    description: 'Final approved furnishing/setup amount',
    icon: 'IconCurrencyRupee',
    isNullable: true,
  },
  {
    type: FieldMetadataType.LINKS,
    name: 'finalInvoice',
    label: 'Final Invoice',
    description: 'Link to the final invoice document',
    icon: 'IconFile',
    isNullable: true,
  },
  {
    type: FieldMetadataType.RICH_TEXT,
    name: 'llExtraClauses',
    label: 'LL Extra Clauses',
    description: 'Extra clauses from the landlord agreement',
    icon: 'IconFileText',
    isNullable: true,
  },

  // --- Payment & Collections ---
  {
    type: FieldMetadataType.SELECT,
    name: 'paymentCollection',
    label: 'Payment Collection',
    description: 'How rent payments are collected',
    icon: 'IconCash',
    options: [
      { label: 'Upfront', value: 'UPFRONT', position: 0, color: 'green' },
      { label: 'Straight Deduction', value: 'STRAIGHT_DEDUCTION', position: 1, color: 'blue' },
      { label: 'EMI', value: 'EMI', position: 2, color: 'yellow' },
    ],
  },
  {
    type: FieldMetadataType.NUMBER,
    name: 'emiPeriod',
    label: 'EMI Period',
    description: 'EMI period in months (if applicable)',
    icon: 'IconCalendar',
    isNullable: true,
    settings: {
      dataType: NumberDataType.INT,
      type: 'number',
    },
  } as FieldMetadataDTO<FieldMetadataType.NUMBER>,
  {
    type: FieldMetadataType.CURRENCY,
    name: 'opexCollections',
    label: 'OPEX Collections',
    description: 'Monthly operating expense collections amount',
    icon: 'IconCurrencyRupee',
    isNullable: true,
  },

  // --- Management ---
  {
    type: FieldMetadataType.SELECT,
    name: 'propMgmtApp',
    label: 'Property Mgmt App',
    description: 'Property management app used',
    icon: 'IconDeviceMobile',
    options: [
      { label: 'MyGate', value: 'MYGATE', position: 0, color: 'blue' },
      { label: 'NoBroker', value: 'NOBROKER', position: 1, color: 'green' },
      { label: 'Apartments.com', value: 'APARTMENTS_COM', position: 2, color: 'purple' },
      { label: 'None', value: 'NONE', position: 3, color: 'red' },
    ],
  },
  {
    type: FieldMetadataType.LINKS,
    name: 'rulesRegulations',
    label: 'Rules & Regulations',
    description: 'Link to property rules and regulations document',
    icon: 'IconFile',
    isNullable: true,
  },
  {
    type: FieldMetadataType.TEXT,
    name: 'garbageDisposal',
    label: 'Garbage Disposal',
    description: 'Garbage disposal instructions',
    icon: 'IconTrash',
    isNullable: true,
    defaultValue: "''",
  },
  {
    type: FieldMetadataType.TEXT,
    name: 'timingRestrictions',
    label: 'Timing Restrictions',
    description: 'Timing-based restrictions (noise, entry, etc.)',
    icon: 'IconClock',
    isNullable: true,
    defaultValue: "''",
  },
  {
    type: FieldMetadataType.RICH_TEXT,
    name: 'moveInOutFormalities',
    label: 'Move In/Out Formalities',
    description: 'Procedures for tenant move-in and move-out',
    icon: 'IconChecklist',
    isNullable: true,
  },

  // --- Deadlines & Dates ---
  {
    type: FieldMetadataType.TEXT,
    name: 'rentDeadline',
    label: 'Rent Deadline',
    description: 'Monthly rent payment deadline (e.g., "5th of every month")',
    icon: 'IconCalendar',
    isNullable: true,
    defaultValue: "''",
  },
  {
    type: FieldMetadataType.TEXT,
    name: 'overheadsDeadline',
    label: 'Overheads Deadline',
    description: 'Monthly overheads payment deadline',
    icon: 'IconCalendar',
    isNullable: true,
    defaultValue: "''",
  },
  {
    type: FieldMetadataType.TEXT,
    name: 'activeDealOwner',
    label: 'Active Deal Owner',
    description: 'Name of the deal owner during active phase',
    icon: 'IconUser',
    isNullable: true,
    defaultValue: "''",
  },
  {
    type: FieldMetadataType.DATE,
    name: 'activationDate',
    label: 'Activation Date',
    description: 'Date when the property was activated',
    icon: 'IconCalendarCheck',
    isNullable: true,
  },
];
