apiVersion: v1
kind: ServiceAccount
metadata:
  name: twenty-server
  namespace: twenty-prod
  annotations:
    iam.gke.io/gcp-service-account: twenty-server@flent-twenty-prod.iam.gserviceaccount.com
  labels:
    app.kubernetes.io/part-of: twenty
