import { FieldMetadataType } from 'twenty-shared/types';

import { type FieldMetadataSeed } from 'src/engine/workspace-manager/dev-seeder/metadata/types/field-metadata-seed.type';

export const MERCHANT_CONTRACT_DETAILS_FIELD_SEEDS: FieldMetadataSeed[] = [
  {
    type: FieldMetadataType.TEXT,
    name: 'partyNameMerchant',
    label: 'Party Name (Merchant)',
    description: 'Derived: merchant first name + last name (landlord only)',
    icon: 'IconBuildingSkyscraper',
    isNullable: false,
    defaultValue: "''",
  },
  {
    type: FieldMetadataType.DATE,
    name: 'keyHandoverDate',
    label: 'Key Handover Date',
    description: 'Date when property keys are handed over',
    icon: 'IconKey',
    isNullable: true,
  },
  {
    type: FieldMetadataType.NUMBER,
    name: 'incrementPercentage',
    label: 'Increment Percentage',
    description: 'Rent increment percentage',
    icon: 'IconTrendingUp',
    isNullable: true,
  },
  {
    type: FieldMetadataType.SELECT,
    name: 'incrementFrequency',
    label: 'Increment Frequency',
    description: 'How often rent is incremented',
    icon: 'IconRepeat',
    options: [
      { label: 'Annual', value: 'ANNUAL', position: 0, color: 'blue' },
      { label: 'Biennial', value: 'BIENNIAL', position: 1, color: 'green' },
      { label: 'None', value: 'NONE', position: 2, color: 'sky' },
    ],
  },
  {
    type: FieldMetadataType.SELECT,
    name: 'agreementStatus',
    label: 'Agreement Status',
    description: 'Current status of the merchant agreement',
    icon: 'IconFileCheck',
    options: [
      { label: 'Negotiation', value: 'NEGOTIATION', position: 0, color: 'yellow' },
      { label: 'Triggered', value: 'TRIGGERED', position: 1, color: 'orange' },
      { label: 'Active', value: 'ACTIVE', position: 2, color: 'green' },
    ],
  },
  {
    type: FieldMetadataType.RAW_JSON,
    name: 'baseRent',
    label: 'Base Rent',
    description:
      'Rent hike schedule as JSONB. Format: [{"month":0,"amount":60000},{"month":12,"amount":66000}]',
    icon: 'IconCurrencyRupee',
    isNullable: false,
  },
  {
    type: FieldMetadataType.CURRENCY,
    name: 'merchantSecurityDeposit',
    label: 'Merchant Security Deposit',
    description: 'Security deposit paid to the merchant/landlord',
    icon: 'IconShield',
    isNullable: true,
  },
  {
    type: FieldMetadataType.CURRENCY,
    name: 'managementFeePerMonth',
    label: 'Management Fee per Month',
    description: 'Monthly management fee',
    icon: 'IconReceipt',
    isNullable: true,
  },
  {
    type: FieldMetadataType.CURRENCY,
    name: 'totalCogs',
    label: 'Total COGS',
    description: 'Derived: base_rent (this contract) + overheads',
    icon: 'IconCalculator',
    isNullable: true,
  },
  {
    type: FieldMetadataType.CURRENCY,
    name: 'contractAcquisitionCost',
    label: 'Contract Acquisition Cost',
    description: 'Cost to acquire this contract',
    icon: 'IconCurrencyRupee',
    isNullable: true,
  },
  {
    type: FieldMetadataType.TEXT,
    name: 'contractAcquisitionCostPaidTo',
    label: 'Acquisition Cost Paid To',
    description: 'Party name the acquisition cost was paid to (not an amount)',
    icon: 'IconUser',
    isNullable: true,
    defaultValue: "''",
  },
  {
    type: FieldMetadataType.SELECT,
    name: 'paymentCycle',
    label: 'Payment Cycle',
    description: 'Payment cycle: Prepaid or Postpaid',
    icon: 'IconRepeat',
    isNullable: false,
    options: [
      { label: 'Prepaid', value: 'PREPAID', position: 0, color: 'blue' },
      { label: 'Postpaid', value: 'POSTPAID', position: 1, color: 'green' },
    ],
  },
  {
    type: FieldMetadataType.DATE,
    name: 'paymentDeadline',
    label: 'Payment Deadline',
    description: 'Deadline date for rent payment',
    icon: 'IconCalendarDue',
    isNullable: false,
  },
  {
    type: FieldMetadataType.LINKS,
    name: 'inventoryList',
    label: 'Inventory List',
    description: 'URL to property inventory list document',
    icon: 'IconList',
    isNullable: true,
  },
];
