import { FieldMetadataType } from 'twenty-shared/types';

import { type FieldMetadataSeed } from 'src/engine/workspace-manager/dev-seeder/metadata/types/field-metadata-seed.type';

export const TENANT_CONTRACT_DETAILS_FIELD_SEEDS: FieldMetadataSeed[] = [
  {
    type: FieldMetadataType.TEXT,
    name: 'partyNameTenant',
    label: 'Party Name (Tenant)',
    description: 'Derived: tenant first name + last name',
    icon: 'IconUser',
    isNullable: false,
    defaultValue: "''",
  },
  {
    type: FieldMetadataType.DATE,
    name: 'preferredMoveOutDate',
    label: 'Preferred Move-out Date',
    description: 'Tenant preferred move-out date',
    icon: 'IconCalendarEvent',
    isNullable: true,
  },
  {
    type: FieldMetadataType.SELECT,
    name: 'paymentLifecycle',
    label: 'Payment Lifecycle',
    description: 'Current payment lifecycle stage',
    icon: 'IconCash',
    options: [
      { label: 'Token Paid', value: 'TOKEN_PAID', position: 0, color: 'sky' },
      { label: 'FMR Paid', value: 'FMR_PAID', position: 1, color: 'blue' },
      { label: 'SD Paid', value: 'SD_PAID', position: 2, color: 'turquoise' },
      { label: 'FMR and SD Cleared', value: 'FMR_AND_SD_CLEARED', position: 3, color: 'green' },
      { label: 'Payments Done', value: 'PAYMENTS_DONE', position: 4, color: 'green' },
    ],
  },
  {
    type: FieldMetadataType.SELECT,
    name: 'agreementLifecycle',
    label: 'Agreement Lifecycle',
    description: 'Current agreement lifecycle stage',
    icon: 'IconFileCheck',
    options: [
      { label: 'L&L and C&S Released', value: 'LL_AND_CS_RELEASED', position: 0, color: 'sky' },
      { label: 'L&L Signed', value: 'LL_SIGNED', position: 1, color: 'blue' },
      { label: 'C&S Signed', value: 'CS_SIGNED', position: 2, color: 'turquoise' },
      { label: 'All Agreements Signed', value: 'ALL_AGREEMENTS_SIGNED', position: 3, color: 'green' },
    ],
  },
  // Rent breakdown (8 fee line items)
  {
    type: FieldMetadataType.CURRENCY,
    name: 'totalRetailRent',
    label: 'Total Retail Rent',
    description: 'Derived sum of all rent components',
    icon: 'IconCurrencyRupee',
    isNullable: true,
  },
  {
    type: FieldMetadataType.CURRENCY,
    name: 'monthlyLicenseFee',
    label: 'Monthly License Fee',
    description: 'Monthly license/rent fee',
    icon: 'IconCurrencyRupee',
    isNullable: true,
  },
  {
    type: FieldMetadataType.CURRENCY,
    name: 'maintenanceFee',
    label: 'Maintenance Fee',
    description: 'Monthly maintenance fee',
    icon: 'IconTool',
    isNullable: true,
  },
  {
    type: FieldMetadataType.CURRENCY,
    name: 'furnishingFee',
    label: 'Furnishing Fee',
    description: 'Monthly furnishing fee',
    icon: 'IconArmchair',
    isNullable: true,
  },
  {
    type: FieldMetadataType.CURRENCY,
    name: 'convenienceFee',
    label: 'Convenience Fee',
    description: 'Monthly convenience/service fee',
    icon: 'IconReceipt',
    isNullable: true,
  },
  {
    type: FieldMetadataType.CURRENCY,
    name: 'gst',
    label: 'GST',
    description: 'Goods and Services Tax amount',
    icon: 'IconReceipt2',
    isNullable: true,
  },
  {
    type: FieldMetadataType.CURRENCY,
    name: 'discountAmount',
    label: 'Discount Amount',
    description: 'Discount applied to total retail rent',
    icon: 'IconDiscount2',
    isNullable: true,
  },
  {
    type: FieldMetadataType.CURRENCY,
    name: 'effectiveRetailRent',
    label: 'Effective Retail Rent',
    description: 'Auto-calculated: total_retail_rent - discount_amount',
    icon: 'IconCalculator',
    isNullable: true,
  },
  // Deposits
  {
    type: FieldMetadataType.CURRENCY,
    name: 'securityDeposit',
    label: 'Security Deposit',
    description: 'Refundable security deposit amount',
    icon: 'IconShield',
    isNullable: true,
  },
  {
    type: FieldMetadataType.CURRENCY,
    name: 'cautionDeposit',
    label: 'Caution Deposit',
    description: 'Caution deposit amount',
    icon: 'IconAlertTriangle',
    isNullable: true,
  },
  // Fees and deductions
  {
    type: FieldMetadataType.CURRENCY,
    name: 'lockInFee',
    label: 'Lock-in Fee',
    description: 'Fee for breaking lock-in period',
    icon: 'IconLock',
    isNullable: true,
  },
  {
    type: FieldMetadataType.CURRENCY,
    name: 'exitFee',
    label: 'Exit Fee',
    description: 'Fee charged upon early exit',
    icon: 'IconDoorExit',
    isNullable: true,
  },
  {
    type: FieldMetadataType.CURRENCY,
    name: 'damagesDeductions',
    label: 'Damages Deductions',
    description: 'Deductions for property damages',
    icon: 'IconAlertCircle',
    isNullable: true,
  },
  {
    type: FieldMetadataType.CURRENCY,
    name: 'societyFees',
    label: 'Society Fees',
    description: 'Housing society fees',
    icon: 'IconBuildingCommunity',
    isNullable: true,
  },
  {
    type: FieldMetadataType.CURRENCY,
    name: 'penalty',
    label: 'Penalty',
    description: 'Penalty charges',
    icon: 'IconGavel',
    isNullable: true,
  },
  {
    type: FieldMetadataType.CURRENCY,
    name: 'totalDeductions',
    label: 'Total Deductions',
    description: 'Auto-calculated: damages_deductions + society_fees + penalty',
    icon: 'IconCalculator',
    isNullable: true,
  },
  // Status fields
  {
    type: FieldMetadataType.TEXT,
    name: 'fmrStatus',
    label: 'FMR Status',
    description: 'First month rent payment status',
    icon: 'IconStatusChange',
    isNullable: true,
    defaultValue: "''",
  },
  {
    type: FieldMetadataType.TEXT,
    name: 'depositPaidStatus',
    label: 'Deposit Paid Status',
    description: 'Deposit payment status',
    icon: 'IconStatusChange',
    isNullable: true,
    defaultValue: "''",
  },
];
