import { FieldMetadataType } from 'twenty-shared/types';

import { type FieldMetadataSeed } from 'src/engine/workspace-manager/dev-seeder/metadata/types/field-metadata-seed.type';

export const TRANSACTION_PURCHASE_ORDER_FIELD_SEEDS: FieldMetadataSeed[] = [
  {
    type: FieldMetadataType.TEXT,
    name: 'poNumber',
    label: 'PO Number',
    description: 'System-generated unique PO identifier',
    icon: 'IconHash',
    isNullable: false,
    defaultValue: "''",
  },
  {
    type: FieldMetadataType.TEXT,
    name: 'vendorCode',
    label: 'Vendor Code',
    description: 'FK to vendors table',
    icon: 'IconTruck',
    isNullable: false,
    defaultValue: "''",
  },
  {
    type: FieldMetadataType.TEXT,
    name: 'vendorName',
    label: 'Vendor Name',
    description: 'Denormalized from vendors.vendor_name on link',
    icon: 'IconTruck',
    isNullable: false,
    defaultValue: "''",
  },
  {
    type: FieldMetadataType.NUMBER,
    name: 'totalItems',
    label: 'Total Items',
    description: 'Total number of line items in the PO',
    icon: 'IconList',
    isNullable: true,
  },
  {
    type: FieldMetadataType.NUMBER,
    name: 'gstPercent',
    label: 'GST %',
    description: 'GST percentage applied to the PO',
    icon: 'IconPercentage',
    isNullable: true,
  },
  {
    type: FieldMetadataType.NUMBER,
    name: 'advanceAmount',
    label: 'Advance Amount',
    description: 'Advance payment amount',
    icon: 'IconCurrencyRupee',
    isNullable: true,
  },
  {
    type: FieldMetadataType.NUMBER,
    name: 'remainingAmount',
    label: 'Remaining Amount',
    description: 'Remaining balance after advance',
    icon: 'IconCurrencyRupee',
    isNullable: true,
  },
  {
    type: FieldMetadataType.DATE,
    name: 'advanceDate',
    label: 'Advance Date',
    description: 'Date of advance payment',
    icon: 'IconCalendar',
    isNullable: true,
  },
  {
    type: FieldMetadataType.DATE,
    name: 'fnfDate',
    label: 'FnF Date',
    description: 'Final and full settlement date',
    icon: 'IconCalendarEvent',
    isNullable: true,
  },
  {
    type: FieldMetadataType.TEXT,
    name: 'invoice',
    label: 'Invoice',
    description: 'File URL for the invoice document',
    icon: 'IconFileInvoice',
    isNullable: true,
    defaultValue: "''",
  },
  {
    type: FieldMetadataType.SELECT,
    name: 'poStatus',
    label: 'PO Status',
    description: 'Purchase order lifecycle status',
    icon: 'IconStatusChange',
    options: [
      { label: 'Draft', value: 'DRAFT', position: 0, color: 'yellow' },
      { label: 'Approved', value: 'APPROVED', position: 1, color: 'blue' },
      { label: 'Completed', value: 'COMPLETED', position: 2, color: 'green' },
      { label: 'Cancelled', value: 'CANCELLED', position: 3, color: 'red' },
    ],
  },
  {
    type: FieldMetadataType.NUMBER,
    name: 'roundOff',
    label: 'Round Off',
    description: 'Sub-rupee adjustment for invoice reconciliation',
    icon: 'IconMathFunction',
    isNullable: true,
  },
  {
    type: FieldMetadataType.TEXT,
    name: 'txnIdAdvance',
    label: 'Advance Transaction UTN',
    description: 'Self-referencing FK to advance payment transaction',
    icon: 'IconArrowDownCircle',
    isNullable: true,
    defaultValue: "''",
  },
  {
    type: FieldMetadataType.TEXT,
    name: 'txnIdRemaining',
    label: 'Remaining Transaction UTN',
    description: 'Self-referencing FK to remaining payment transaction',
    icon: 'IconArrowUpCircle',
    isNullable: true,
    defaultValue: "''",
  },
];
