import { FieldMetadataType } from 'twenty-shared/types';

import { type FieldMetadataSeed } from 'src/engine/workspace-manager/dev-seeder/metadata/types/field-metadata-seed.type';

export const MERCHANT_FIELD_SEEDS: FieldMetadataSeed[] = [
  {
    type: FieldMetadataType.SELECT,
    name: 'merchantType',
    label: 'Merchant Type',
    description: 'Type of merchant relationship',
    icon: 'IconCategory',
    options: [
      { label: 'Landlord', value: 'LANDLORD', position: 0, color: 'blue' },
      { label: 'POC', value: 'POC', position: 1, color: 'green' },
      { label: 'Lead', value: 'LEAD', position: 2, color: 'yellow' },
      { label: 'Broker', value: 'BROKER', position: 3, color: 'purple' },
      { label: 'Management', value: 'MANAGEMENT', position: 4, color: 'orange' },
    ],
  },
  {
    type: FieldMetadataType.SELECT,
    name: 'prefix',
    label: 'Prefix',
    description: 'Name prefix / salutation',
    icon: 'IconUser',
    options: [
      { label: 'Mr', value: 'MR', position: 0, color: 'blue' },
      { label: 'Mrs', value: 'MRS', position: 1, color: 'pink' },
      { label: 'Ms', value: 'MS', position: 2, color: 'purple' },
      { label: 'Dr', value: 'DR', position: 3, color: 'green' },
    ],
  },
  {
    type: FieldMetadataType.FULL_NAME,
    name: 'name',
    label: 'Name',
    description: "Merchant's full name",
    icon: 'IconUser',
    isNullable: false,
  },
  {
    type: FieldMetadataType.EMAILS,
    name: 'emails',
    label: 'Email',
    description: "Merchant's email address",
    icon: 'IconMail',
    isNullable: true,
  },
  {
    type: FieldMetadataType.PHONES,
    name: 'phones',
    label: 'Phone',
    description: "Merchant's phone numbers with country code",
    icon: 'IconPhone',
    isNullable: false,
  },
  {
    type: FieldMetadataType.TEXT,
    name: 'currentCity',
    label: 'Current City',
    description: "Merchant's current city of residence",
    icon: 'IconMapPin',
    isNullable: true,
    defaultValue: "''",
  },
  {
    type: FieldMetadataType.SELECT,
    name: 'leadSource',
    label: 'Lead Source',
    description: 'How this merchant was sourced',
    icon: 'IconTarget',
    options: [
      { label: 'Referral', value: 'REFERRAL', position: 0, color: 'green' },
      { label: 'Direct', value: 'DIRECT', position: 1, color: 'blue' },
      { label: 'Broker', value: 'BROKER', position: 2, color: 'purple' },
      { label: 'Online', value: 'ONLINE', position: 3, color: 'sky' },
      { label: 'Cold Outreach', value: 'COLD_OUTREACH', position: 4, color: 'yellow' },
      { label: 'Platform', value: 'PLATFORM', position: 5, color: 'orange' },
    ],
  },
  {
    type: FieldMetadataType.TEXT,
    name: 'uniqueId',
    label: 'Unique ID',
    description: 'External unique identifier for the merchant',
    icon: 'IconId',
    isNullable: true,
    isUnique: true,
    defaultValue: "''",
  },
  {
    type: FieldMetadataType.SELECT,
    name: 'disqualificationReason',
    label: 'Disqualification Reason',
    description: 'Reason the merchant was disqualified',
    icon: 'IconAlertCircle',
    options: [
      { label: 'Price Mismatch', value: 'PRICE_MISMATCH', position: 0, color: 'yellow' },
      { label: 'Property Condition', value: 'PROPERTY_CONDITION', position: 1, color: 'orange' },
      { label: 'Location', value: 'LOCATION', position: 2, color: 'blue' },
      { label: 'Unresponsive', value: 'UNRESPONSIVE', position: 3, color: 'red' },
      { label: 'Regulatory', value: 'REGULATORY', position: 4, color: 'purple' },
      { label: 'Other', value: 'OTHER', position: 5, color: 'sky' },
    ],
  },
  {
    type: FieldMetadataType.SELECT,
    name: 'lostReason',
    label: 'Lost Reason',
    description: 'Reason the merchant deal was lost',
    icon: 'IconThumbDown',
    options: [
      { label: 'Chose Competitor', value: 'CHOSE_COMPETITOR', position: 0, color: 'red' },
      { label: 'Price', value: 'PRICE', position: 1, color: 'yellow' },
      { label: 'Timing', value: 'TIMING', position: 2, color: 'orange' },
      { label: 'Not Interested', value: 'NOT_INTERESTED', position: 3, color: 'red' },
      { label: 'Other', value: 'OTHER', position: 4, color: 'sky' },
    ],
  },
];
