import { FieldMetadataType } from 'twenty-shared/types';

import { type FieldMetadataSeed } from 'src/engine/workspace-manager/dev-seeder/metadata/types/field-metadata-seed.type';

export const MERCHANT_LANDLORD_FIELD_SEEDS: FieldMetadataSeed[] = [
  {
    type: FieldMetadataType.RICH_TEXT,
    name: 'landlordPersonality',
    label: 'Landlord Personality',
    description: 'Notes about landlord personality and communication style',
    icon: 'IconMoodSmile',
    isNullable: true,
  },
  {
    type: FieldMetadataType.RICH_TEXT,
    name: 'generalLlComments',
    label: 'General LL Comments',
    description: 'General comments and notes about the landlord',
    icon: 'IconNote',
    isNullable: true,
  },
  {
    type: FieldMetadataType.BOOLEAN,
    name: 'potentiallyMultihome',
    label: 'Potentially Multi-home',
    description: 'Whether the landlord may have multiple properties',
    icon: 'IconBuildingCommunity',
    isNullable: true,
    defaultValue: false,
  },
  {
    type: FieldMetadataType.TEXT,
    name: 'designation',
    label: 'Designation',
    description: "Landlord's professional designation",
    icon: 'IconBriefcase',
    isNullable: true,
    defaultValue: "''",
  },
  {
    type: FieldMetadataType.TEXT,
    name: 'organization',
    label: 'Organization',
    description: "Landlord's organization or company",
    icon: 'IconBuilding',
    isNullable: true,
    defaultValue: "''",
  },
  {
    type: FieldMetadataType.LINKS,
    name: 'aadhaarBack',
    label: 'Aadhaar Back',
    description: 'URL to Aadhaar card back image',
    icon: 'IconPhoto',
    isNullable: true,
  },
  {
    type: FieldMetadataType.TEXT,
    name: 'panNumber',
    label: 'PAN Number',
    description: "Landlord's PAN number",
    icon: 'IconId',
    isNullable: true,
    defaultValue: "''",
  },
  {
    type: FieldMetadataType.LINKS,
    name: 'panCardImage',
    label: 'PAN Card Image',
    description: 'URL to PAN card image',
    icon: 'IconPhoto',
    isNullable: true,
  },
  {
    type: FieldMetadataType.TEXT,
    name: 'bankAccountNumber',
    label: 'Bank Account Number',
    description: "Landlord's bank account number",
    icon: 'IconCreditCard',
    isNullable: true,
    defaultValue: "''",
  },
  {
    type: FieldMetadataType.TEXT,
    name: 'beneficiaryName',
    label: 'Beneficiary Name',
    description: 'Bank account beneficiary name',
    icon: 'IconUser',
    isNullable: true,
    defaultValue: "''",
  },
  {
    type: FieldMetadataType.TEXT,
    name: 'ifscCode',
    label: 'IFSC Code',
    description: 'Bank IFSC code',
    icon: 'IconBuildingBank',
    isNullable: true,
    defaultValue: "''",
  },
  {
    type: FieldMetadataType.RICH_TEXT,
    name: 'currentResidential',
    label: 'Current Residential Address',
    description: "Landlord's current residential address",
    icon: 'IconMapPin',
    isNullable: true,
  },
  {
    type: FieldMetadataType.RICH_TEXT,
    name: 'permanentResidential',
    label: 'Permanent Residential Address',
    description: "Landlord's permanent residential address",
    icon: 'IconMapPin',
    isNullable: true,
  },
  {
    type: FieldMetadataType.BOOLEAN,
    name: 'communicationsPermission',
    label: 'Communications Permission',
    description: 'Whether the landlord has given communications consent',
    icon: 'IconBell',
    isNullable: true,
    defaultValue: false,
  },
  {
    type: FieldMetadataType.BOOLEAN,
    name: 'signingAuthority',
    label: 'Signing Authority',
    description: 'Whether the landlord has signing authority',
    icon: 'IconPencil',
    isNullable: true,
    defaultValue: false,
  },
  {
    type: FieldMetadataType.LINKS,
    name: 'linkedinUrl',
    label: 'LinkedIn',
    description: "Landlord's LinkedIn profile URL",
    icon: 'IconBrandLinkedin',
    isNullable: true,
  },
];
