apiVersion: v1
kind: Service
metadata:
  name: pgbouncer-service
  namespace: twenty-prod
  labels:
    app: pgbouncer
    app.kubernetes.io/part-of: twenty
    app.kubernetes.io/component: database-proxy
spec:
  type: ClusterIP
  selector:
    app: pgbouncer
  ports:
    - name: pgbouncer
      port: 6432
      targetPort: 6432
      protocol: TCP
