// ─── Realistic dummy data for Flemp — Full-Stack Rental Housing Operations ──

// ─── PROPERTIES (PID) ───────────────────────────────────────────────────────

export const PROPERTIES = [
    { id: "PID-001", name: "Indiranagar Residency", address: "12 CMH Road, Indiranagar", city: "Bangalore", type: "Apartment" as const, totalUnits: 8, occupiedUnits: 7, rent: "₹18,000", status: "Partial" as const, landlord: "Suresh Iyer", landlordPhone: "+91 99001 10011", landlordEmail: "suresh.iyer@gmail.com", furnishing: "Fully Furnished", maintenanceFee: "₹2,500", securityDeposit: "₹36,000", lockInMonths: 11, wifi: { provider: "ACT Fibernet", speed: "100 Mbps" }, electricity: { provider: "BESCOM", accountNo: "4520018976" }, water: "Borewell + Municipal", dealOwner: "Srashti Jain", psmOwner: "Nisha Mehta", merchantId: "MER-001", cluster: "IDR" as const, dealStage: "Under Contract" as const, propertyType: "Residence Lead" as const, tier: "T1", floor: "2nd", parking: "Two-Wheeler", powerBackup: "Inverter", rentDeadline: "5", maintenanceDeadline: "5", overheadsDeadline: "10" },
    { id: "PID-002", name: "Koramangala Heights", address: "45 80ft Road, Koramangala", city: "Bangalore", type: "Coliving" as const, totalUnits: 12, occupiedUnits: 12, rent: "₹12,000", status: "Full" as const, landlord: "Meena Reddy", landlordPhone: "+91 99002 20022", landlordEmail: "meena.reddy@yahoo.com", furnishing: "Fully Furnished", maintenanceFee: "₹1,800", securityDeposit: "₹24,000", lockInMonths: 6, wifi: { provider: "Airtel Xstream", speed: "200 Mbps" }, electricity: { provider: "BESCOM", accountNo: "4520023451" }, water: "Municipal", dealOwner: "Srashti Jain", psmOwner: "Karthik Rajan", merchantId: "MER-002", cluster: "KRM" as const, dealStage: "Under Contract" as const, propertyType: "Residence Lead" as const, tier: "T1", floor: "3rd", parking: "Car + Two-Wheeler", powerBackup: "Generator", rentDeadline: "1", maintenanceDeadline: "1", overheadsDeadline: "5" },
    { id: "PID-003", name: "HSR Green Villas", address: "78 Sector 2, HSR Layout", city: "Bangalore", type: "Apartment" as const, totalUnits: 6, occupiedUnits: 5, rent: "₹22,000", status: "Partial" as const, landlord: "Ramesh Babu", landlordPhone: "+91 99003 30033", landlordEmail: "ramesh.b@outlook.com", furnishing: "Semi Furnished", maintenanceFee: "₹3,000", securityDeposit: "₹44,000", lockInMonths: 11, wifi: { provider: "Jio Fiber", speed: "150 Mbps" }, electricity: { provider: "BESCOM", accountNo: "4520034567" }, water: "Borewell", dealOwner: "Nisha Mehta", psmOwner: "Nisha Mehta", merchantId: "MER-003", cluster: "HSR" as const, dealStage: "Under Contract" as const, propertyType: "Residence Lead" as const, tier: "T2", floor: "1st", parking: "Two-Wheeler", powerBackup: "Inverter", rentDeadline: "5", maintenanceDeadline: "5", overheadsDeadline: "10" },
    { id: "PID-004", name: "Whitefield Studio Hub", address: "3 ITPL Main Rd, Whitefield", city: "Bangalore", type: "Studio" as const, totalUnits: 20, occupiedUnits: 16, rent: "₹9,500", status: "Partial" as const, landlord: "Anita Sharma", landlordPhone: "+91 99004 40044", landlordEmail: "anita.sharma@gmail.com", furnishing: "Fully Furnished", maintenanceFee: "₹1,500", securityDeposit: "₹19,000", lockInMonths: 6, wifi: { provider: "ACT Fibernet", speed: "100 Mbps" }, electricity: { provider: "BESCOM", accountNo: "4520045678" }, water: "Municipal", dealOwner: "Srashti Jain", psmOwner: "Karthik Rajan", merchantId: "MER-004", cluster: "WHF" as const, dealStage: "Under Contract" as const, propertyType: "Residence Lead" as const, tier: "T2", floor: "Ground + 1st", parking: "Car", powerBackup: "Generator", rentDeadline: "1", maintenanceDeadline: "1", overheadsDeadline: "5" },
    { id: "PID-005", name: "JP Nagar Palm Court", address: "99 15th Cross, JP Nagar", city: "Bangalore", type: "Apartment" as const, totalUnits: 10, occupiedUnits: 10, rent: "₹15,000", status: "Full" as const, landlord: "Kiran Desai", landlordPhone: "+91 99005 50055", landlordEmail: "kiran.d@gmail.com", furnishing: "Fully Furnished", maintenanceFee: "₹2,000", securityDeposit: "₹30,000", lockInMonths: 11, wifi: { provider: "Airtel Xstream", speed: "100 Mbps" }, electricity: { provider: "BESCOM", accountNo: "4520056789" }, water: "Municipal + Tanker", dealOwner: "Nisha Mehta", psmOwner: "Nisha Mehta", merchantId: "MER-005", cluster: "MGR" as const, dealStage: "Under Contract" as const, propertyType: "Residence Lead" as const, tier: "T1", floor: "2nd", parking: "Car + Two-Wheeler", powerBackup: "Generator", rentDeadline: "5", maintenanceDeadline: "5", overheadsDeadline: "10" },
    { id: "PID-006", name: "BTM Lake View", address: "22 Lake Rd, BTM Layout", city: "Bangalore", type: "Apartment" as const, totalUnits: 4, occupiedUnits: 3, rent: "₹14,000", status: "Partial" as const, landlord: "Deepa Nair", landlordPhone: "+91 99006 60066", landlordEmail: "deepa.nair@gmail.com", furnishing: "Semi Furnished", maintenanceFee: "₹2,200", securityDeposit: "₹28,000", lockInMonths: 11, wifi: { provider: "Jio Fiber", speed: "100 Mbps" }, electricity: { provider: "BESCOM", accountNo: "4520067890" }, water: "Borewell", dealOwner: "Srashti Jain", psmOwner: "Karthik Rajan", merchantId: "MER-006", cluster: "HSR" as const, dealStage: "Under Contract" as const, propertyType: "Residence Lead" as const, tier: "T2", floor: "1st", parking: "Two-Wheeler", powerBackup: "Inverter", rentDeadline: "5", maintenanceDeadline: "5", overheadsDeadline: "10" },
    { id: "PID-007", name: "Marathahalli Silver Oaks", address: "56 ORR Service Rd, Marathahalli", city: "Bangalore", type: "Coliving" as const, totalUnits: 15, occupiedUnits: 11, rent: "₹10,000", status: "Partial" as const, landlord: "Vijay Kumar", landlordPhone: "+91 99007 70077", landlordEmail: "vijay.k@outlook.com", furnishing: "Fully Furnished", maintenanceFee: "₹1,600", securityDeposit: "₹20,000", lockInMonths: 6, wifi: { provider: "ACT Fibernet", speed: "150 Mbps" }, electricity: { provider: "BESCOM", accountNo: "4520078901" }, water: "Municipal", dealOwner: "Nisha Mehta", psmOwner: "Nisha Mehta", merchantId: "MER-007", cluster: "MHD" as const, dealStage: "Under Contract" as const, propertyType: "Residence Lead" as const, tier: "T2", floor: "Ground", parking: "None", powerBackup: "None", rentDeadline: "1", maintenanceDeadline: "1", overheadsDeadline: "5" },
    { id: "PID-008", name: "Banashankari Emerald", address: "10 Bull Temple Rd, Banashankari", city: "Bangalore", type: "Apartment" as const, totalUnits: 6, occupiedUnits: 0, rent: "₹20,000", status: "Available" as const, landlord: "Lakshmi Rao", landlordPhone: "+91 99008 80088", landlordEmail: "lakshmi.rao@gmail.com", furnishing: "Unfurnished", maintenanceFee: "₹2,800", securityDeposit: "₹40,000", lockInMonths: 11, wifi: { provider: "—", speed: "—" }, electricity: { provider: "BESCOM", accountNo: "4520089012" }, water: "Borewell + Municipal", dealOwner: "Srashti Jain", psmOwner: "—", merchantId: "MER-008", cluster: "BLD" as const, dealStage: "Negotiations Started" as const, propertyType: "Residence Lead" as const, tier: "T3", floor: "3rd", parking: "Car", powerBackup: "None", rentDeadline: "—", maintenanceDeadline: "—", overheadsDeadline: "—" },
    { id: "PID-009", name: "Electronic City Horizon", address: "88 Neeladri Rd, Electronic City", city: "Bangalore", type: "Studio" as const, totalUnits: 18, occupiedUnits: 14, rent: "₹8,500", status: "Partial" as const, landlord: "Preethi Menon", landlordPhone: "+91 99009 90099", landlordEmail: "preethi.m@yahoo.com", furnishing: "Fully Furnished", maintenanceFee: "₹1,200", securityDeposit: "₹17,000", lockInMonths: 6, wifi: { provider: "Airtel Xstream", speed: "100 Mbps" }, electricity: { provider: "BESCOM", accountNo: "4520090123" }, water: "Municipal", dealOwner: "Karthik Rajan", psmOwner: "Karthik Rajan", merchantId: "MER-009", cluster: "HBL" as const, dealStage: "Under Contract" as const, propertyType: "Residence Lead" as const, tier: "T2", floor: "1st + 2nd", parking: "Two-Wheeler", powerBackup: "Inverter", rentDeadline: "1", maintenanceDeadline: "1", overheadsDeadline: "5" },
    { id: "PID-010", name: "Yelahanka Cedar Homes", address: "17 Air Force Rd, Yelahanka", city: "Bangalore", type: "Apartment" as const, totalUnits: 5, occupiedUnits: 4, rent: "₹13,000", status: "Partial" as const, landlord: "Arun Pillai", landlordPhone: "+91 99010 10010", landlordEmail: "arun.p@gmail.com", furnishing: "Semi Furnished", maintenanceFee: "₹2,000", securityDeposit: "₹26,000", lockInMonths: 11, wifi: { provider: "Jio Fiber", speed: "100 Mbps" }, electricity: { provider: "BESCOM", accountNo: "4520001234" }, water: "Borewell", dealOwner: "Nisha Mehta", psmOwner: "Nisha Mehta", merchantId: "MER-010", cluster: "HBL" as const, dealStage: "Under Contract" as const, propertyType: "Residence Lead" as const, tier: "T3", floor: "2nd", parking: "Car", powerBackup: "Inverter", rentDeadline: "5", maintenanceDeadline: "5", overheadsDeadline: "10" },
    { id: "PID-011", name: "Jayanagar Rose Garden", address: "34 11th Cross, Jayanagar", city: "Bangalore", type: "Apartment" as const, totalUnits: 4, occupiedUnits: 4, rent: "₹25,000", status: "Full" as const, landlord: "Mohan Das", landlordPhone: "+91 99011 11011", landlordEmail: "mohan.d@outlook.com", furnishing: "Fully Furnished", maintenanceFee: "₹3,500", securityDeposit: "₹50,000", lockInMonths: 11, wifi: { provider: "ACT Fibernet", speed: "200 Mbps" }, electricity: { provider: "BESCOM", accountNo: "4520012345" }, water: "Municipal + Tanker", dealOwner: "Srashti Jain", psmOwner: "Karthik Rajan", merchantId: "MER-011", cluster: "MGR" as const, dealStage: "Under Contract" as const, propertyType: "Residence Lead" as const, tier: "T1", floor: "1st", parking: "Car + Two-Wheeler", powerBackup: "Generator", rentDeadline: "1", maintenanceDeadline: "1", overheadsDeadline: "5" },
    // Lead-stage properties (not yet active)
    { id: "PID-012", name: "Sarjapur Road Residency", address: "120 Sarjapur Main Rd", city: "Bangalore", type: "Apartment" as const, totalUnits: 8, occupiedUnits: 0, rent: "₹16,000", status: "Available" as const, landlord: "Ganesh Hegde", landlordPhone: "+91 99012 12012", landlordEmail: "ganesh.h@gmail.com", furnishing: "Semi Furnished", maintenanceFee: "₹2,000", securityDeposit: "₹32,000", lockInMonths: 11, wifi: { provider: "—", speed: "—" }, electricity: { provider: "BESCOM", accountNo: "—" }, water: "Borewell", dealOwner: "Srashti Jain", psmOwner: "—", merchantId: "MER-012", cluster: "HSR" as const, dealStage: "Evaluation" as const, propertyType: "Residence Lead" as const, tier: "—", floor: "2nd + 3rd", parking: "Car", powerBackup: "Generator", rentDeadline: "—", maintenanceDeadline: "—", overheadsDeadline: "—" },
    { id: "PID-013", name: "Hennur Gardens", address: "45 Hennur Main Rd", city: "Bangalore", type: "Coliving" as const, totalUnits: 10, occupiedUnits: 0, rent: "₹11,000", status: "Available" as const, landlord: "Pooja Shetty", landlordPhone: "+91 99013 13013", landlordEmail: "pooja.s@gmail.com", furnishing: "Unfurnished", maintenanceFee: "₹1,500", securityDeposit: "₹22,000", lockInMonths: 6, wifi: { provider: "—", speed: "—" }, electricity: { provider: "BESCOM", accountNo: "—" }, water: "Municipal", dealOwner: "Nisha Mehta", psmOwner: "—", merchantId: "MER-013", cluster: "HBL" as const, dealStage: "Qualified" as const, propertyType: "Residence Lead" as const, tier: "—", floor: "Ground + 1st", parking: "Two-Wheeler", powerBackup: "None", rentDeadline: "—", maintenanceDeadline: "—", overheadsDeadline: "—" },
    { id: "PID-014", name: "Bellandur Tech Park View", address: "88 Outer Ring Rd, Bellandur", city: "Bangalore", type: "Studio" as const, totalUnits: 24, occupiedUnits: 0, rent: "₹9,000", status: "Available" as const, landlord: "Rajesh Nambiar", landlordPhone: "+91 99014 14014", landlordEmail: "rajesh.n@outlook.com", furnishing: "Unfurnished", maintenanceFee: "₹1,200", securityDeposit: "₹18,000", lockInMonths: 6, wifi: { provider: "—", speed: "—" }, electricity: { provider: "BESCOM", accountNo: "—" }, water: "Municipal", dealOwner: "Srashti Jain", psmOwner: "—", merchantId: "MER-014", cluster: "MHD" as const, dealStage: "To be contacted" as const, propertyType: "Residence Lead" as const, tier: "—", floor: "1st–4th", parking: "Car + Two-Wheeler", powerBackup: "Generator", rentDeadline: "—", maintenanceDeadline: "—", overheadsDeadline: "—" },
];

// ─── ROOMS (RID) ────────────────────────────────────────────────────────────

export const ROOMS = [
    { id: "RID-001-A", pid: "PID-001", attachedBathroom: true, balcony: false, bedType: "Double" as const, ac: true, acType: "Split" as const, studyTable: true, baseRent: 18000, maintenanceFee: 2500, roomStatus: "Occupied" as const, currentContractId: "TC-001", currentTenantName: "Rahul Sharma", availableFrom: "—" },
    { id: "RID-001-B", pid: "PID-001", attachedBathroom: true, balcony: true, bedType: "Queen" as const, ac: true, acType: "Split" as const, studyTable: true, baseRent: 20000, maintenanceFee: 2500, roomStatus: "Occupied" as const, currentContractId: "TC-011", currentTenantName: "Sneha Kulkarni", availableFrom: "—" },
    { id: "RID-001-C", pid: "PID-001", attachedBathroom: false, balcony: false, bedType: "Single" as const, ac: false, acType: "Not Possible" as const, studyTable: true, baseRent: 15000, maintenanceFee: 2500, roomStatus: "Available" as const, currentContractId: null, currentTenantName: "—", availableFrom: "2026-05-01" },
    { id: "RID-002-A", pid: "PID-002", attachedBathroom: false, balcony: false, bedType: "Single" as const, ac: false, acType: "Window" as const, studyTable: false, baseRent: 12000, maintenanceFee: 1800, roomStatus: "Occupied" as const, currentContractId: "TC-003", currentTenantName: "Priya Singh", availableFrom: "—" },
    { id: "RID-002-B", pid: "PID-002", attachedBathroom: false, balcony: false, bedType: "Single" as const, ac: false, acType: "Window" as const, studyTable: true, baseRent: 12000, maintenanceFee: 1800, roomStatus: "Occupied" as const, currentContractId: null, currentTenantName: "Anil Mathur", availableFrom: "—" },
    { id: "RID-003-A", pid: "PID-003", attachedBathroom: true, balcony: true, bedType: "King" as const, ac: true, acType: "Split" as const, studyTable: true, baseRent: 22000, maintenanceFee: 3000, roomStatus: "Occupied" as const, currentContractId: "TC-002", currentTenantName: "Amit Kumar", availableFrom: "—" },
    { id: "RID-003-B", pid: "PID-003", attachedBathroom: true, balcony: false, bedType: "Double" as const, ac: true, acType: "Split" as const, studyTable: true, baseRent: 20000, maintenanceFee: 3000, roomStatus: "Available" as const, currentContractId: null, currentTenantName: "—", availableFrom: "2026-04-20" },
    { id: "RID-004-A", pid: "PID-004", attachedBathroom: true, balcony: false, bedType: "Single" as const, ac: true, acType: "Window" as const, studyTable: true, baseRent: 9500, maintenanceFee: 1500, roomStatus: "Occupied" as const, currentContractId: "TC-006", currentTenantName: "Vikram Rao", availableFrom: "—" },
    { id: "RID-005-A", pid: "PID-005", attachedBathroom: true, balcony: true, bedType: "Double" as const, ac: true, acType: "Split" as const, studyTable: true, baseRent: 15000, maintenanceFee: 2000, roomStatus: "Occupied" as const, currentContractId: "TC-005", currentTenantName: "Neha Gupta", availableFrom: "—" },
    { id: "RID-006-A", pid: "PID-006", attachedBathroom: true, balcony: false, bedType: "Double" as const, ac: false, acType: "Portable" as const, studyTable: true, baseRent: 14000, maintenanceFee: 2200, roomStatus: "Occupied" as const, currentContractId: "TC-004", currentTenantName: "Sanjay Patel", availableFrom: "—" },
    { id: "RID-006-B", pid: "PID-006", attachedBathroom: false, balcony: false, bedType: "Single" as const, ac: false, acType: "Not Possible" as const, studyTable: false, baseRent: 12000, maintenanceFee: 2200, roomStatus: "Available" as const, currentContractId: null, currentTenantName: "—", availableFrom: "2026-04-15" },
    { id: "RID-007-A", pid: "PID-007", attachedBathroom: false, balcony: false, bedType: "Single" as const, ac: false, acType: "Window" as const, studyTable: false, baseRent: 10000, maintenanceFee: 1600, roomStatus: "Occupied" as const, currentContractId: "TC-009", currentTenantName: "Kavita Joshi", availableFrom: "—" },
    { id: "RID-008-A", pid: "PID-008", attachedBathroom: true, balcony: true, bedType: "King" as const, ac: true, acType: "Split" as const, studyTable: true, baseRent: 20000, maintenanceFee: 2800, roomStatus: "Under Maintenance" as const, currentContractId: null, currentTenantName: "—", availableFrom: "2026-06-01" },
    { id: "RID-009-A", pid: "PID-009", attachedBathroom: true, balcony: false, bedType: "Single" as const, ac: true, acType: "Window" as const, studyTable: true, baseRent: 8500, maintenanceFee: 1200, roomStatus: "Occupied" as const, currentContractId: "TC-007", currentTenantName: "Divya Menon", availableFrom: "—" },
    { id: "RID-010-A", pid: "PID-010", attachedBathroom: true, balcony: false, bedType: "Double" as const, ac: false, acType: "Portable" as const, studyTable: true, baseRent: 13000, maintenanceFee: 2000, roomStatus: "Occupied" as const, currentContractId: "TC-008", currentTenantName: "Arjun Nair", availableFrom: "—" },
    { id: "RID-011-A", pid: "PID-011", attachedBathroom: true, balcony: true, bedType: "King" as const, ac: true, acType: "Split" as const, studyTable: true, baseRent: 25000, maintenanceFee: 3500, roomStatus: "Occupied" as const, currentContractId: "TC-010", currentTenantName: "Ravi Prasad", availableFrom: "—" },
];

// ─── MERCHANTS ──────────────────────────────────────────────────────────────

export const MERCHANTS = [
    { id: "MER-001", firstName: "Suresh", lastName: "Iyer", email: "suresh.iyer@gmail.com", phone: "+91 99001 10011", city: "Bangalore", leadSource: "Referral", prefix: "Mr" as const, activeProperties: 1, status: "Active" as const, panNumber: "ABCPI1234A", bankAccount: "XXXX5678", ifscCode: "SBIN0001234", signingAuthority: true, firstAdded: "2025-06-15" },
    { id: "MER-002", firstName: "Meena", lastName: "Reddy", email: "meena.reddy@yahoo.com", phone: "+91 99002 20022", city: "Bangalore", leadSource: "Direct Call", prefix: "Mrs" as const, activeProperties: 1, status: "Active" as const, panNumber: "DEFPR5678B", bankAccount: "XXXX9012", ifscCode: "HDFC0005678", signingAuthority: true, firstAdded: "2025-05-20" },
    { id: "MER-003", firstName: "Ramesh", lastName: "Babu", email: "ramesh.b@outlook.com", phone: "+91 99003 30033", city: "Bangalore", leadSource: "Walk-in", prefix: "Mr" as const, activeProperties: 1, status: "Active" as const, panNumber: "GHIRB9012C", bankAccount: "XXXX3456", ifscCode: "ICIC0009012", signingAuthority: true, firstAdded: "2025-07-01" },
    { id: "MER-004", firstName: "Anita", lastName: "Sharma", email: "anita.sharma@gmail.com", phone: "+91 99004 40044", city: "Bangalore", leadSource: "Referral", prefix: "Mrs" as const, activeProperties: 1, status: "Active" as const, panNumber: "JKLAS3456D", bankAccount: "XXXX7890", ifscCode: "AXIS0003456", signingAuthority: true, firstAdded: "2025-08-10" },
    { id: "MER-005", firstName: "Kiran", lastName: "Desai", email: "kiran.d@gmail.com", phone: "+91 99005 50055", city: "Bangalore", leadSource: "Broker", prefix: "Mr" as const, activeProperties: 1, status: "Active" as const, panNumber: "MNOKD7890E", bankAccount: "XXXX1234", ifscCode: "UTIB0007890", signingAuthority: false, firstAdded: "2025-04-15" },
    { id: "MER-006", firstName: "Deepa", lastName: "Nair", email: "deepa.nair@gmail.com", phone: "+91 99006 60066", city: "Bangalore", leadSource: "Platform", prefix: "Mrs" as const, activeProperties: 1, status: "Active" as const, panNumber: "PQRDN1234F", bankAccount: "XXXX5678", ifscCode: "KKBK0001234", signingAuthority: true, firstAdded: "2025-09-01" },
    { id: "MER-007", firstName: "Vijay", lastName: "Kumar", email: "vijay.k@outlook.com", phone: "+91 99007 70077", city: "Bangalore", leadSource: "Direct Call", prefix: "Mr" as const, activeProperties: 1, status: "Active" as const, panNumber: "STUVK5678G", bankAccount: "XXXX9012", ifscCode: "SBIN0005678", signingAuthority: true, firstAdded: "2025-06-20" },
    { id: "MER-008", firstName: "Lakshmi", lastName: "Rao", email: "lakshmi.rao@gmail.com", phone: "+91 99008 80088", city: "Bangalore", leadSource: "Walk-in", prefix: "Mrs" as const, activeProperties: 1, status: "Lead" as const, panNumber: "WXYLR9012H", bankAccount: "—", ifscCode: "—", signingAuthority: false, firstAdded: "2026-01-10" },
    { id: "MER-009", firstName: "Preethi", lastName: "Menon", email: "preethi.m@yahoo.com", phone: "+91 99009 90099", city: "Bangalore", leadSource: "Referral", prefix: "Ms" as const, activeProperties: 1, status: "Active" as const, panNumber: "ABCPM3456I", bankAccount: "XXXX3456", ifscCode: "HDFC0009012", signingAuthority: true, firstAdded: "2025-05-10" },
    { id: "MER-010", firstName: "Arun", lastName: "Pillai", email: "arun.p@gmail.com", phone: "+91 99010 10010", city: "Bangalore", leadSource: "Broker", prefix: "Mr" as const, activeProperties: 1, status: "Active" as const, panNumber: "DEFAP7890J", bankAccount: "XXXX7890", ifscCode: "ICIC0003456", signingAuthority: true, firstAdded: "2025-07-15" },
    { id: "MER-011", firstName: "Mohan", lastName: "Das", email: "mohan.d@outlook.com", phone: "+91 99011 11011", city: "Bangalore", leadSource: "Direct Call", prefix: "Mr" as const, activeProperties: 1, status: "Active" as const, panNumber: "GHIMD1234K", bankAccount: "XXXX1234", ifscCode: "AXIS0007890", signingAuthority: true, firstAdded: "2025-04-01" },
    { id: "MER-012", firstName: "Ganesh", lastName: "Hegde", email: "ganesh.h@gmail.com", phone: "+91 99012 12012", city: "Bangalore", leadSource: "Referral", prefix: "Mr" as const, activeProperties: 0, status: "Lead" as const, panNumber: "—", bankAccount: "—", ifscCode: "—", signingAuthority: false, firstAdded: "2026-02-01" },
    { id: "MER-013", firstName: "Pooja", lastName: "Shetty", email: "pooja.s@gmail.com", phone: "+91 99013 13013", city: "Bangalore", leadSource: "Platform", prefix: "Ms" as const, activeProperties: 0, status: "Lead" as const, panNumber: "—", bankAccount: "—", ifscCode: "—", signingAuthority: false, firstAdded: "2026-03-05" },
    { id: "MER-014", firstName: "Rajesh", lastName: "Nambiar", email: "rajesh.n@outlook.com", phone: "+91 99014 14014", city: "Bangalore", leadSource: "Walk-in", prefix: "Mr" as const, activeProperties: 0, status: "Lead" as const, panNumber: "—", bankAccount: "—", ifscCode: "—", signingAuthority: false, firstAdded: "2026-03-20" },
];

// ─── TENANTS ────────────────────────────────────────────────────────────────

export const TENANTS = [
    { id: "TEN-001", name: "Rahul Sharma", firstName: "Rahul", lastName: "Sharma", phone: "+91 98765 43210", email: "rahul.sharma@gmail.com", gender: "Male" as const, occupation: "Senior Developer", employer: "Infosys", propertyId: "PID-001", propertyName: "Indiranagar Residency", rid: "RID-001-A", rentalStatus: "Active" as const, moveIn: "Jan 15, 2026", idProof: "Aadhaar – XXXX 4521", emergencyContact: "+91 98765 11111", contractStart: "Jan 15, 2026", contractEnd: "Jan 14, 2027", lockInMonths: 11, rentAmount: "₹18,000", securityDeposit: "₹36,000", lifecycle: "Moved In" as const, qualificationStatus: "Qualified" as const, bgvStatus: "Passed" as const, channel: "Website" as const, sourceDD1: "Google Ads" as const, budget: 20000, preferredArea: "Indiranagar", onboardingCsat: 4, lastNps: 8, npsCategory: "Passive" as const },
    { id: "TEN-002", name: "Amit Kumar", firstName: "Amit", lastName: "Kumar", phone: "+91 87654 32109", email: "amit.kumar@gmail.com", gender: "Male" as const, occupation: "Data Analyst", employer: "Wipro", propertyId: "PID-003", propertyName: "HSR Green Villas", rid: "RID-003-A", rentalStatus: "Active" as const, moveIn: "Feb 1, 2026", idProof: "Aadhaar – XXXX 8734", emergencyContact: "+91 87654 22222", contractStart: "Feb 1, 2026", contractEnd: "Jan 31, 2027", lockInMonths: 11, rentAmount: "₹22,000", securityDeposit: "₹44,000", lifecycle: "Moved In" as const, qualificationStatus: "Qualified" as const, bgvStatus: "Passed" as const, channel: "WhatsApp" as const, sourceDD1: "Referral" as const, budget: 25000, preferredArea: "HSR Layout", onboardingCsat: 5, lastNps: 9, npsCategory: "Promoter" as const },
    { id: "TEN-003", name: "Priya Singh", firstName: "Priya", lastName: "Singh", phone: "+91 76543 21098", email: "priya.singh@yahoo.com", gender: "Female" as const, occupation: "Product Manager", employer: "Flipkart", propertyId: "PID-002", propertyName: "Koramangala Heights", rid: "RID-002-A", rentalStatus: "Active" as const, moveIn: "Dec 10, 2025", idProof: "PAN – ABCPS1234R", emergencyContact: "+91 76543 33333", contractStart: "Dec 10, 2025", contractEnd: "Dec 9, 2026", lockInMonths: 6, rentAmount: "₹12,000", securityDeposit: "₹24,000", lifecycle: "Moved In" as const, qualificationStatus: "Qualified" as const, bgvStatus: "Passed" as const, channel: "Instagram" as const, sourceDD1: "Meta Ads" as const, budget: 15000, preferredArea: "Koramangala", onboardingCsat: 4, lastNps: 7, npsCategory: "Passive" as const },
    { id: "TEN-004", name: "Sanjay Patel", firstName: "Sanjay", lastName: "Patel", phone: "+91 65432 10987", email: "sanjay.patel@outlook.com", gender: "Male" as const, occupation: "Solutions Architect", employer: "TCS", propertyId: "PID-006", propertyName: "BTM Lake View", rid: "RID-006-A", rentalStatus: "Active" as const, moveIn: "Mar 1, 2026", idProof: "Aadhaar – XXXX 6712", emergencyContact: "+91 65432 44444", contractStart: "Mar 1, 2026", contractEnd: "Feb 28, 2027", lockInMonths: 11, rentAmount: "₹14,000", securityDeposit: "₹28,000", lifecycle: "Moved In" as const, qualificationStatus: "Qualified" as const, bgvStatus: "Passed" as const, channel: "Direct Call" as const, sourceDD1: "Direct Call" as const, budget: 16000, preferredArea: "BTM Layout", onboardingCsat: 3, lastNps: 6, npsCategory: "Detractor" as const },
    { id: "TEN-005", name: "Neha Gupta", firstName: "Neha", lastName: "Gupta", phone: "+91 54321 09876", email: "neha.gupta@gmail.com", gender: "Female" as const, occupation: "SDE-II", employer: "Amazon", propertyId: "PID-005", propertyName: "JP Nagar Palm Court", rid: "RID-005-A", rentalStatus: "Active" as const, moveIn: "Nov 20, 2025", idProof: "Aadhaar – XXXX 9023", emergencyContact: "+91 54321 55555", contractStart: "Nov 20, 2025", contractEnd: "Nov 19, 2026", lockInMonths: 11, rentAmount: "₹15,000", securityDeposit: "₹30,000", lifecycle: "Moved In" as const, qualificationStatus: "Qualified" as const, bgvStatus: "Passed" as const, channel: "Website" as const, sourceDD1: "Housing.com" as const, budget: 18000, preferredArea: "JP Nagar", onboardingCsat: 5, lastNps: 10, npsCategory: "Promoter" as const },
    { id: "TEN-006", name: "Vikram Rao", firstName: "Vikram", lastName: "Rao", phone: "+91 43210 98765", email: "vikram.rao@gmail.com", gender: "Male" as const, occupation: "UI Designer", employer: "Swiggy", propertyId: "PID-004", propertyName: "Whitefield Studio Hub", rid: "RID-004-A", rentalStatus: "Active" as const, moveIn: "Jan 5, 2026", idProof: "Passport – M1234567", emergencyContact: "+91 43210 66666", contractStart: "Jan 5, 2026", contractEnd: "Jul 4, 2026", lockInMonths: 6, rentAmount: "₹9,500", securityDeposit: "₹19,000", lifecycle: "Moved In" as const, qualificationStatus: "Qualified" as const, bgvStatus: "Passed" as const, channel: "Platform" as const, sourceDD1: "NoBroker" as const, budget: 12000, preferredArea: "Whitefield", onboardingCsat: 4, lastNps: 8, npsCategory: "Passive" as const },
    { id: "TEN-007", name: "Divya Menon", firstName: "Divya", lastName: "Menon", phone: "+91 32109 87654", email: "divya.menon@gmail.com", gender: "Female" as const, occupation: "Embedded Engineer", employer: "Bosch", propertyId: "PID-009", propertyName: "Electronic City Horizon", rid: "RID-009-A", rentalStatus: "Active" as const, moveIn: "Feb 15, 2026", idProof: "Aadhaar – XXXX 3456", emergencyContact: "+91 32109 77777", contractStart: "Feb 15, 2026", contractEnd: "Aug 14, 2026", lockInMonths: 6, rentAmount: "₹8,500", securityDeposit: "₹17,000", lifecycle: "Moved In" as const, qualificationStatus: "Qualified" as const, bgvStatus: "Passed" as const, channel: "WhatsApp" as const, sourceDD1: "WhatsApp Organic" as const, budget: 10000, preferredArea: "Electronic City", onboardingCsat: 4, lastNps: 9, npsCategory: "Promoter" as const },
    { id: "TEN-008", name: "Arjun Nair", firstName: "Arjun", lastName: "Nair", phone: "+91 21098 76543", email: "arjun.nair@yahoo.com", gender: "Male" as const, occupation: "Cloud Engineer", employer: "SAP Labs", propertyId: "PID-010", propertyName: "Yelahanka Cedar Homes", rid: "RID-010-A", rentalStatus: "Active" as const, moveIn: "Mar 10, 2026", idProof: "Aadhaar – XXXX 7890", emergencyContact: "+91 21098 88888", contractStart: "Mar 10, 2026", contractEnd: "Mar 9, 2027", lockInMonths: 11, rentAmount: "₹13,000", securityDeposit: "₹26,000", lifecycle: "Moved In" as const, qualificationStatus: "Qualified" as const, bgvStatus: "Passed" as const, channel: "Walk-in" as const, sourceDD1: "Walk-in" as const, budget: 15000, preferredArea: "Yelahanka", onboardingCsat: 3, lastNps: 7, npsCategory: "Passive" as const },
    { id: "TEN-009", name: "Kavita Joshi", firstName: "Kavita", lastName: "Joshi", phone: "+91 10987 65432", email: "kavita.joshi@gmail.com", gender: "Female" as const, occupation: "QA Lead", employer: "Mindtree", propertyId: "PID-007", propertyName: "Marathahalli Silver Oaks", rid: "RID-007-A", rentalStatus: "Active" as const, moveIn: "Jan 20, 2026", idProof: "Aadhaar – XXXX 2345", emergencyContact: "+91 10987 99999", contractStart: "Jan 20, 2026", contractEnd: "Jul 19, 2026", lockInMonths: 6, rentAmount: "₹10,000", securityDeposit: "₹20,000", lifecycle: "Moved In" as const, qualificationStatus: "Qualified" as const, bgvStatus: "Passed" as const, channel: "Referral" as const, sourceDD1: "Referral" as const, budget: 12000, preferredArea: "Marathahalli", onboardingCsat: 5, lastNps: 9, npsCategory: "Promoter" as const },
    { id: "TEN-010", name: "Ravi Prasad", firstName: "Ravi", lastName: "Prasad", phone: "+91 99887 76655", email: "ravi.prasad@outlook.com", gender: "Male" as const, occupation: "DB Administrator", employer: "Oracle", propertyId: "PID-011", propertyName: "Jayanagar Rose Garden", rid: "RID-011-A", rentalStatus: "Active" as const, moveIn: "Dec 1, 2025", idProof: "Aadhaar – XXXX 5678", emergencyContact: "+91 99887 00000", contractStart: "Dec 1, 2025", contractEnd: "Nov 30, 2026", lockInMonths: 11, rentAmount: "₹25,000", securityDeposit: "₹50,000", lifecycle: "Moved In" as const, qualificationStatus: "Qualified" as const, bgvStatus: "Passed" as const, channel: "Website" as const, sourceDD1: "Google Ads" as const, budget: 28000, preferredArea: "Jayanagar", onboardingCsat: 4, lastNps: 8, npsCategory: "Passive" as const },
    { id: "TEN-011", name: "Sneha Kulkarni", firstName: "Sneha", lastName: "Kulkarni", phone: "+91 88776 65544", email: "sneha.k@gmail.com", gender: "Female" as const, occupation: "Business Analyst", employer: "Accenture", propertyId: "PID-001", propertyName: "Indiranagar Residency", rid: "RID-001-B", rentalStatus: "Active" as const, moveIn: "Feb 20, 2026", idProof: "PAN – BCDSK5678Q", emergencyContact: "+91 88776 11100", contractStart: "Feb 20, 2026", contractEnd: "Feb 19, 2027", lockInMonths: 11, rentAmount: "₹20,000", securityDeposit: "₹40,000", lifecycle: "Moved In" as const, qualificationStatus: "Qualified" as const, bgvStatus: "Passed" as const, channel: "Instagram" as const, sourceDD1: "Meta Ads" as const, budget: 22000, preferredArea: "Indiranagar", onboardingCsat: 5, lastNps: 10, npsCategory: "Promoter" as const },
    // Lead-stage tenants
    { id: "TEN-012", name: "Manoj Tiwari", firstName: "Manoj", lastName: "Tiwari", phone: "+91 77665 54433", email: "manoj.t@yahoo.com", gender: "Male" as const, occupation: "Graphic Designer", employer: "Freelancer", propertyId: null, propertyName: "—", rid: null, rentalStatus: "Pending" as const, moveIn: "—", idProof: "Aadhaar – XXXX 1122", emergencyContact: "+91 77665 22200", contractStart: "—", contractEnd: "—", lockInMonths: 0, rentAmount: "—", securityDeposit: "—", lifecycle: "New Inquiry" as const, qualificationStatus: null, bgvStatus: "Not Started" as const, channel: "WhatsApp" as const, sourceDD1: "WhatsApp Organic" as const, budget: 10000, preferredArea: "Koramangala", onboardingCsat: null, lastNps: null, npsCategory: null },
    { id: "TEN-013", name: "Anjali Verma", firstName: "Anjali", lastName: "Verma", phone: "+91 66554 43322", email: "anjali.v@gmail.com", gender: "Female" as const, occupation: "SWE-III", employer: "Google", propertyId: null, propertyName: "—", rid: null, rentalStatus: "Pending" as const, moveIn: "—", idProof: "Passport – N7654321", emergencyContact: "+91 66554 33300", contractStart: "—", contractEnd: "—", lockInMonths: 0, rentAmount: "—", securityDeposit: "—", lifecycle: "Visit Scheduled" as const, qualificationStatus: null, bgvStatus: "Not Started" as const, channel: "Website" as const, sourceDD1: "Google Ads" as const, budget: 30000, preferredArea: "Indiranagar", onboardingCsat: null, lastNps: null, npsCategory: null },
    { id: "TEN-014", name: "Deepak Hegde", firstName: "Deepak", lastName: "Hegde", phone: "+91 55443 32211", email: "deepak.h@outlook.com", gender: "Male" as const, occupation: "Network Engineer", employer: "HCL", propertyId: "PID-002", propertyName: "Koramangala Heights", rid: null, rentalStatus: "Past" as const, moveIn: "Jun 1, 2025", idProof: "Aadhaar – XXXX 9900", emergencyContact: "+91 55443 44400", contractStart: "Jun 1, 2025", contractEnd: "Nov 30, 2025", lockInMonths: 6, rentAmount: "₹12,000", securityDeposit: "₹24,000", lifecycle: "Moved Out" as const, qualificationStatus: "Qualified" as const, bgvStatus: "Passed" as const, channel: "Direct Call" as const, sourceDD1: "Direct Call" as const, budget: 14000, preferredArea: "Koramangala", onboardingCsat: 3, lastNps: 5, npsCategory: "Detractor" as const },
    // More lead-stage tenants for pipeline
    { id: "TEN-015", name: "Rohan Mehra", firstName: "Rohan", lastName: "Mehra", phone: "+91 44332 21100", email: "rohan.m@gmail.com", gender: "Male" as const, occupation: "Marketing Manager", employer: "Zomato", propertyId: null, propertyName: "—", rid: null, rentalStatus: "Pending" as const, moveIn: "—", idProof: "—", emergencyContact: "—", contractStart: "—", contractEnd: "—", lockInMonths: 0, rentAmount: "—", securityDeposit: "—", lifecycle: "Visit Done" as const, qualificationStatus: "Qualified" as const, bgvStatus: "Not Started" as const, channel: "Instagram" as const, sourceDD1: "Meta Ads" as const, budget: 18000, preferredArea: "HSR Layout", onboardingCsat: null, lastNps: null, npsCategory: null },
    { id: "TEN-016", name: "Meera Iyer", firstName: "Meera", lastName: "Iyer", phone: "+91 33221 10099", email: "meera.i@yahoo.com", gender: "Female" as const, occupation: "UX Researcher", employer: "Microsoft", propertyId: null, propertyName: "—", rid: null, rentalStatus: "Pending" as const, moveIn: "—", idProof: "—", emergencyContact: "—", contractStart: "—", contractEnd: "—", lockInMonths: 0, rentAmount: "—", securityDeposit: "—", lifecycle: "Negotiation" as const, qualificationStatus: "Qualified" as const, bgvStatus: "Not Started" as const, channel: "Website" as const, sourceDD1: "Housing.com" as const, budget: 22000, preferredArea: "Indiranagar", onboardingCsat: null, lastNps: null, npsCategory: null },
    { id: "TEN-017", name: "Aditya Rao", firstName: "Aditya", lastName: "Rao", phone: "+91 22110 09988", email: "aditya.r@gmail.com", gender: "Male" as const, occupation: "DevOps Engineer", employer: "Atlassian", propertyId: null, propertyName: "—", rid: null, rentalStatus: "Pending" as const, moveIn: "—", idProof: "—", emergencyContact: "—", contractStart: "—", contractEnd: "—", lockInMonths: 0, rentAmount: "—", securityDeposit: "—", lifecycle: "Converted" as const, qualificationStatus: "Qualified" as const, bgvStatus: "In Progress" as const, channel: "Referral" as const, sourceDD1: "Referral" as const, budget: 16000, preferredArea: "Whitefield", onboardingCsat: null, lastNps: null, npsCategory: null },
    { id: "TEN-018", name: "Pooja Nair", firstName: "Pooja", lastName: "Nair", phone: "+91 11009 98877", email: "pooja.n@outlook.com", gender: "Female" as const, occupation: "Content Writer", employer: "Freshworks", propertyId: null, propertyName: "—", rid: null, rentalStatus: "Pending" as const, moveIn: "—", idProof: "—", emergencyContact: "—", contractStart: "—", contractEnd: "—", lockInMonths: 0, rentAmount: "—", securityDeposit: "—", lifecycle: "Gestation" as const, qualificationStatus: "Qualified" as const, bgvStatus: "Passed" as const, channel: "WhatsApp" as const, sourceDD1: "WhatsApp Organic" as const, budget: 12000, preferredArea: "Koramangala", onboardingCsat: null, lastNps: null, npsCategory: null },
    { id: "TEN-019", name: "Karthik Bhat", firstName: "Karthik", lastName: "Bhat", phone: "+91 99887 77665", email: "karthik.b@gmail.com", gender: "Male" as const, occupation: "Full Stack Dev", employer: "Razorpay", propertyId: null, propertyName: "—", rid: null, rentalStatus: "Pending" as const, moveIn: "—", idProof: "—", emergencyContact: "—", contractStart: "—", contractEnd: "—", lockInMonths: 0, rentAmount: "—", securityDeposit: "—", lifecycle: "Dead Lead" as const, qualificationStatus: "Dead" as const, bgvStatus: "Not Started" as const, channel: "Website" as const, sourceDD1: "99acres" as const, budget: 8000, preferredArea: "Electronic City", onboardingCsat: null, lastNps: null, npsCategory: null },
];

// ─── TENANT CONTRACTS ───────────────────────────────────────────────────────

export const TENANT_CONTRACTS = [
    { id: "TC-001", tenantId: "TEN-001", tenantName: "Rahul Sharma", merchantId: "MER-001", merchantName: "Suresh Iyer", pid: "PID-001", pidName: "Indiranagar Residency", rid: "RID-001-A", contractType: "L&L" as const, startDate: "2026-01-15", endDate: "2027-01-14", lockIn: 11, lockInEndDate: "2026-12-15", totalRetailRent: 18000, monthlyLicenseFee: 18000, maintenanceFee: 2500, furnishingFee: 0, convenienceFee: 500, gst: 0, discount: 0, effectiveRent: 18000, securityDeposit: 36000, cautionDeposit: 0, lockInFee: 0, exitFee: 5000, noticePeriod: 2, paymentLifecycle: "Payments Done" as const, agreementLifecycle: "C&S Signed" as const, fmrStatus: "Paid" as const, status: "Active" as const },
    { id: "TC-002", tenantId: "TEN-002", tenantName: "Amit Kumar", merchantId: "MER-003", merchantName: "Ramesh Babu", pid: "PID-003", pidName: "HSR Green Villas", rid: "RID-003-A", contractType: "L&L" as const, startDate: "2026-02-01", endDate: "2027-01-31", lockIn: 11, lockInEndDate: "2027-01-01", totalRetailRent: 22000, monthlyLicenseFee: 22000, maintenanceFee: 3000, furnishingFee: 0, convenienceFee: 500, gst: 0, discount: 0, effectiveRent: 22000, securityDeposit: 44000, cautionDeposit: 0, lockInFee: 0, exitFee: 5000, noticePeriod: 2, paymentLifecycle: "Payments Done" as const, agreementLifecycle: "C&S Signed" as const, fmrStatus: "Paid" as const, status: "Active" as const },
    { id: "TC-003", tenantId: "TEN-003", tenantName: "Priya Singh", merchantId: "MER-002", merchantName: "Meena Reddy", pid: "PID-002", pidName: "Koramangala Heights", rid: "RID-002-A", contractType: "L&L" as const, startDate: "2025-12-10", endDate: "2026-12-09", lockIn: 6, lockInEndDate: "2026-06-10", totalRetailRent: 12000, monthlyLicenseFee: 12000, maintenanceFee: 1800, furnishingFee: 0, convenienceFee: 300, gst: 0, discount: 0, effectiveRent: 12000, securityDeposit: 24000, cautionDeposit: 0, lockInFee: 0, exitFee: 3000, noticePeriod: 1, paymentLifecycle: "Payments Done" as const, agreementLifecycle: "C&S Signed" as const, fmrStatus: "Paid" as const, status: "Active" as const },
    { id: "TC-004", tenantId: "TEN-004", tenantName: "Sanjay Patel", merchantId: "MER-006", merchantName: "Deepa Nair", pid: "PID-006", pidName: "BTM Lake View", rid: "RID-006-A", contractType: "L&L" as const, startDate: "2026-03-01", endDate: "2027-02-28", lockIn: 11, lockInEndDate: "2027-02-01", totalRetailRent: 14000, monthlyLicenseFee: 14000, maintenanceFee: 2200, furnishingFee: 0, convenienceFee: 500, gst: 0, discount: 0, effectiveRent: 14000, securityDeposit: 28000, cautionDeposit: 0, lockInFee: 0, exitFee: 5000, noticePeriod: 2, paymentLifecycle: "Payments Done" as const, agreementLifecycle: "C&S Signed" as const, fmrStatus: "Paid" as const, status: "Active" as const },
    { id: "TC-005", tenantId: "TEN-005", tenantName: "Neha Gupta", merchantId: "MER-005", merchantName: "Kiran Desai", pid: "PID-005", pidName: "JP Nagar Palm Court", rid: "RID-005-A", contractType: "L&L" as const, startDate: "2025-11-20", endDate: "2026-11-19", lockIn: 11, lockInEndDate: "2026-10-20", totalRetailRent: 15000, monthlyLicenseFee: 15000, maintenanceFee: 2000, furnishingFee: 0, convenienceFee: 500, gst: 0, discount: 0, effectiveRent: 15000, securityDeposit: 30000, cautionDeposit: 0, lockInFee: 0, exitFee: 5000, noticePeriod: 2, paymentLifecycle: "Payments Done" as const, agreementLifecycle: "C&S Signed" as const, fmrStatus: "Paid" as const, status: "Active" as const },
    { id: "TC-006", tenantId: "TEN-006", tenantName: "Vikram Rao", merchantId: "MER-004", merchantName: "Anita Sharma", pid: "PID-004", pidName: "Whitefield Studio Hub", rid: "RID-004-A", contractType: "C&S" as const, startDate: "2026-01-05", endDate: "2026-07-04", lockIn: 6, lockInEndDate: "2026-07-04", totalRetailRent: 9500, monthlyLicenseFee: 9500, maintenanceFee: 1500, furnishingFee: 0, convenienceFee: 300, gst: 0, discount: 0, effectiveRent: 9500, securityDeposit: 19000, cautionDeposit: 0, lockInFee: 0, exitFee: 3000, noticePeriod: 1, paymentLifecycle: "Payments Done" as const, agreementLifecycle: "C&S Signed" as const, fmrStatus: "Paid" as const, status: "Active" as const },
    { id: "TC-007", tenantId: "TEN-007", tenantName: "Divya Menon", merchantId: "MER-009", merchantName: "Preethi Menon", pid: "PID-009", pidName: "Electronic City Horizon", rid: "RID-009-A", contractType: "C&S" as const, startDate: "2026-02-15", endDate: "2026-08-14", lockIn: 6, lockInEndDate: "2026-08-14", totalRetailRent: 8500, monthlyLicenseFee: 8500, maintenanceFee: 1200, furnishingFee: 0, convenienceFee: 300, gst: 0, discount: 0, effectiveRent: 8500, securityDeposit: 17000, cautionDeposit: 0, lockInFee: 0, exitFee: 3000, noticePeriod: 1, paymentLifecycle: "Payments Done" as const, agreementLifecycle: "C&S Signed" as const, fmrStatus: "Paid" as const, status: "Active" as const },
    { id: "TC-008", tenantId: "TEN-008", tenantName: "Arjun Nair", merchantId: "MER-010", merchantName: "Arun Pillai", pid: "PID-010", pidName: "Yelahanka Cedar Homes", rid: "RID-010-A", contractType: "L&L" as const, startDate: "2026-03-10", endDate: "2027-03-09", lockIn: 11, lockInEndDate: "2027-02-10", totalRetailRent: 13000, monthlyLicenseFee: 13000, maintenanceFee: 2000, furnishingFee: 0, convenienceFee: 500, gst: 0, discount: 0, effectiveRent: 13000, securityDeposit: 26000, cautionDeposit: 0, lockInFee: 0, exitFee: 5000, noticePeriod: 2, paymentLifecycle: "Payments Done" as const, agreementLifecycle: "C&S Signed" as const, fmrStatus: "Paid" as const, status: "Active" as const },
    { id: "TC-009", tenantId: "TEN-009", tenantName: "Kavita Joshi", merchantId: "MER-007", merchantName: "Vijay Kumar", pid: "PID-007", pidName: "Marathahalli Silver Oaks", rid: "RID-007-A", contractType: "C&S" as const, startDate: "2026-01-20", endDate: "2026-07-19", lockIn: 6, lockInEndDate: "2026-07-19", totalRetailRent: 10000, monthlyLicenseFee: 10000, maintenanceFee: 1600, furnishingFee: 0, convenienceFee: 300, gst: 0, discount: 0, effectiveRent: 10000, securityDeposit: 20000, cautionDeposit: 0, lockInFee: 0, exitFee: 3000, noticePeriod: 1, paymentLifecycle: "Payments Done" as const, agreementLifecycle: "C&S Signed" as const, fmrStatus: "Paid" as const, status: "Active" as const },
    { id: "TC-010", tenantId: "TEN-010", tenantName: "Ravi Prasad", merchantId: "MER-011", merchantName: "Mohan Das", pid: "PID-011", pidName: "Jayanagar Rose Garden", rid: "RID-011-A", contractType: "L&L" as const, startDate: "2025-12-01", endDate: "2026-11-30", lockIn: 11, lockInEndDate: "2026-11-01", totalRetailRent: 25000, monthlyLicenseFee: 25000, maintenanceFee: 3500, furnishingFee: 0, convenienceFee: 500, gst: 0, discount: 0, effectiveRent: 25000, securityDeposit: 50000, cautionDeposit: 0, lockInFee: 0, exitFee: 5000, noticePeriod: 2, paymentLifecycle: "Payments Done" as const, agreementLifecycle: "C&S Signed" as const, fmrStatus: "Paid" as const, status: "Active" as const },
    { id: "TC-011", tenantId: "TEN-011", tenantName: "Sneha Kulkarni", merchantId: "MER-001", merchantName: "Suresh Iyer", pid: "PID-001", pidName: "Indiranagar Residency", rid: "RID-001-B", contractType: "L&L" as const, startDate: "2026-02-20", endDate: "2027-02-19", lockIn: 11, lockInEndDate: "2027-01-20", totalRetailRent: 20000, monthlyLicenseFee: 20000, maintenanceFee: 2500, furnishingFee: 0, convenienceFee: 500, gst: 0, discount: 2000, effectiveRent: 18000, securityDeposit: 40000, cautionDeposit: 0, lockInFee: 0, exitFee: 5000, noticePeriod: 2, paymentLifecycle: "Payments Done" as const, agreementLifecycle: "C&S Signed" as const, fmrStatus: "Paid" as const, status: "Active" as const },
];

// ─── MERCHANT CONTRACTS ─────────────────────────────────────────────────────

export const MERCHANT_CONTRACTS = [
    { id: "MC-001", pid: "PID-001", pidName: "Indiranagar Residency", merchantId: "MER-001", merchantName: "Suresh Iyer", baseRent: 55000, securityDeposit: 110000, startDate: "2025-06-15", endDate: "2027-06-14", serviceTerm: "24 months", incrementPct: 5, incrementFrequency: "Annual", managementFee: 5000, paymentCycle: "Postpaid" as const, agreementStatus: "Active" as const, totalCogs: 60000, keyHandoverDate: "2025-06-20" },
    { id: "MC-002", pid: "PID-002", pidName: "Koramangala Heights", merchantId: "MER-002", merchantName: "Meena Reddy", baseRent: 90000, securityDeposit: 180000, startDate: "2025-05-20", endDate: "2027-05-19", serviceTerm: "24 months", incrementPct: 5, incrementFrequency: "Annual", managementFee: 8000, paymentCycle: "Prepaid" as const, agreementStatus: "Active" as const, totalCogs: 98000, keyHandoverDate: "2025-05-25" },
    { id: "MC-003", pid: "PID-003", pidName: "HSR Green Villas", merchantId: "MER-003", merchantName: "Ramesh Babu", baseRent: 75000, securityDeposit: 150000, startDate: "2025-07-01", endDate: "2027-06-30", serviceTerm: "24 months", incrementPct: 5, incrementFrequency: "Annual", managementFee: 6000, paymentCycle: "Postpaid" as const, agreementStatus: "Active" as const, totalCogs: 81000, keyHandoverDate: "2025-07-05" },
    { id: "MC-004", pid: "PID-004", pidName: "Whitefield Studio Hub", merchantId: "MER-004", merchantName: "Anita Sharma", baseRent: 120000, securityDeposit: 240000, startDate: "2025-08-10", endDate: "2027-08-09", serviceTerm: "24 months", incrementPct: 5, incrementFrequency: "Annual", managementFee: 10000, paymentCycle: "Prepaid" as const, agreementStatus: "Active" as const, totalCogs: 130000, keyHandoverDate: "2025-08-15" },
    { id: "MC-005", pid: "PID-005", pidName: "JP Nagar Palm Court", merchantId: "MER-005", merchantName: "Kiran Desai", baseRent: 100000, securityDeposit: 200000, startDate: "2025-04-15", endDate: "2027-04-14", serviceTerm: "24 months", incrementPct: 5, incrementFrequency: "Annual", managementFee: 8000, paymentCycle: "Postpaid" as const, agreementStatus: "Active" as const, totalCogs: 108000, keyHandoverDate: "2025-04-20" },
];

// ─── TICKETS ────────────────────────────────────────────────────────────────

export const TICKETS = [
    { id: "TKT-001", pipeline: "Tenant" as const, createdBy: "TEN-001", createdByName: "Rahul Sharma", pid: "PID-001", pidName: "Indiranagar Residency", rid: "RID-001-A", ticketName: "Leaking kitchen faucet", ticketDescription: "Kitchen faucet has been leaking since morning, water pooling on counter.", category: "Plumbing" as const, priority: "High" as const, status: "Waiting on Vendor" as const, owner: "srashti@flent.in", assignedVendor: "VEN-001", assignedVendorName: "AquaFix Plumbing", createDate: "2026-04-08", costPaidByFlent: 1200, collectedFromTenant: 0, collectedFromMerchant: 0, totalCost: 1200, slaHoursRemaining: 4, tenantRating: null, csatFeedback: null, resolutionNotes: null },
    { id: "TKT-002", pipeline: "Tenant" as const, createdBy: "TEN-003", createdByName: "Priya Singh", pid: "PID-002", pidName: "Koramangala Heights", rid: "RID-002-A", ticketName: "AC not cooling", ticketDescription: "Split AC in bedroom not cooling properly, warm air blowing.", category: "Appliance" as const, priority: "Medium" as const, status: "New Request" as const, owner: "cs@flent.in", assignedVendor: null, assignedVendorName: null, createDate: "2026-04-10", costPaidByFlent: 0, collectedFromTenant: 0, collectedFromMerchant: 0, totalCost: 0, slaHoursRemaining: 18, tenantRating: null, csatFeedback: null, resolutionNotes: null },
    { id: "TKT-003", pipeline: "Tenant" as const, createdBy: "TEN-005", createdByName: "Neha Gupta", pid: "PID-005", pidName: "JP Nagar Palm Court", rid: "RID-005-A", ticketName: "Broken wardrobe hinge", ticketDescription: "Wardrobe door hinge broken, door falling off.", category: "Carpentry" as const, priority: "Low" as const, status: "Closed" as const, owner: "srashti@flent.in", assignedVendor: "VEN-003", assignedVendorName: "WoodCraft Solutions", createDate: "2026-03-25", costPaidByFlent: 800, collectedFromTenant: 0, collectedFromMerchant: 800, totalCost: 0, slaHoursRemaining: 0, tenantRating: 5, csatFeedback: "Very quick resolution, thank you!", resolutionNotes: "Replaced hinge and tightened all screws. Wardrobe door functioning normally." },
    { id: "TKT-004", pipeline: "Tenant" as const, createdBy: "TEN-002", createdByName: "Amit Kumar", pid: "PID-003", pidName: "HSR Green Villas", rid: "RID-003-A", ticketName: "WiFi speed extremely slow", ticketDescription: "Internet speed dropped to 5 Mbps, was supposed to be 150 Mbps.", category: "Utility" as const, priority: "High" as const, status: "Waiting on Product" as const, owner: "cs@flent.in", assignedVendor: null, assignedVendorName: null, createDate: "2026-04-09", costPaidByFlent: 0, collectedFromTenant: 0, collectedFromMerchant: 0, totalCost: 0, slaHoursRemaining: 6, tenantRating: null, csatFeedback: null, resolutionNotes: null },
    { id: "TKT-005", pipeline: "Tenant" as const, createdBy: "TEN-004", createdByName: "Sanjay Patel", pid: "PID-006", pidName: "BTM Lake View", rid: "RID-006-A", ticketName: "Power socket not working", ticketDescription: "Bedroom power socket sparking and not functional.", category: "Electrical" as const, priority: "Urgent" as const, status: "Waiting on Vendor" as const, owner: "srashti@flent.in", assignedVendor: "VEN-002", assignedVendorName: "SparkElectric Co.", createDate: "2026-04-11", costPaidByFlent: 0, collectedFromTenant: 0, collectedFromMerchant: 0, totalCost: 0, slaHoursRemaining: 2, tenantRating: null, csatFeedback: null, resolutionNotes: null },
    { id: "TKT-006", pipeline: "Vendor/Landlord" as const, createdBy: "PSM", createdByName: "Nisha Mehta", pid: "PID-007", pidName: "Marathahalli Silver Oaks", rid: null, ticketName: "Society maintenance arrears", ticketDescription: "Society demanding 3 months maintenance arrears — landlord to settle.", category: "Utility" as const, priority: "Medium" as const, status: "Waiting on Landlord" as const, owner: "cs@flent.in", assignedVendor: null, assignedVendorName: null, createDate: "2026-04-05", costPaidByFlent: 0, collectedFromTenant: 0, collectedFromMerchant: 0, totalCost: 0, slaHoursRemaining: 48, tenantRating: null, csatFeedback: null, resolutionNotes: null },
    { id: "TKT-007", pipeline: "Tenant" as const, createdBy: "TEN-009", createdByName: "Kavita Joshi", pid: "PID-007", pidName: "Marathahalli Silver Oaks", rid: "RID-007-A", ticketName: "Water heater not working", ticketDescription: "Geyser in bathroom not heating water at all.", category: "Appliance" as const, priority: "High" as const, status: "Ready for Closure" as const, owner: "srashti@flent.in", assignedVendor: "VEN-001", assignedVendorName: "AquaFix Plumbing", createDate: "2026-04-02", costPaidByFlent: 2500, collectedFromTenant: 0, collectedFromMerchant: 2500, totalCost: 0, slaHoursRemaining: 0, tenantRating: 4, csatFeedback: "Took a bit long but fixed well.", resolutionNotes: "Replaced heating element. Tested and working." },
    { id: "TKT-008", pipeline: "Tenant" as const, createdBy: "TEN-010", createdByName: "Ravi Prasad", pid: "PID-011", pidName: "Jayanagar Rose Garden", rid: "RID-011-A", ticketName: "Reimbursement for pest control", ticketDescription: "Had to call pest control urgently due to cockroach infestation. Receipt attached.", category: "Reimbursement" as const, priority: "Low" as const, status: "Waiting for Payment" as const, owner: "cs@flent.in", assignedVendor: null, assignedVendorName: null, createDate: "2026-04-07", costPaidByFlent: 1500, collectedFromTenant: 0, collectedFromMerchant: 0, totalCost: 1500, slaHoursRemaining: 24, tenantRating: null, csatFeedback: null, resolutionNotes: "Reimbursement approved. Awaiting payment processing." },
];

// ─── TRANSACTIONS ───────────────────────────────────────────────────────────

export const TRANSACTIONS = [
    // Rent collections (Credit)
    { id: "TXN-20260401-00001", creditDebit: "Credit" as const, date: "2026-04-01", amount: 18000, status: "Completed" as const, purpose1: "REVENUE" as const, purpose2: "Rent" as const, typeDetails: "Standard" as const, fromParty: "Rahul Sharma", fromPartyType: "Tenant" as const, toParty: "Flent", toPartyType: "Platform" as const, paymentChannel: "UPI" as const, paymentProvider: "Razorpayx" as const, gatewayRef: "pay_abc123456", settlementRef: "UTR1234567890", createdBy: "System", authorisedBy: "—", contractUid: "TC-001", contactId: "TEN-001", pid: "PID-001", rid: "RID-001-A", merchantId: null, vendorCode: null, lineItemDesc: "Monthly Rent – Apr 2026" },
    { id: "TXN-20260401-00002", creditDebit: "Credit" as const, date: "2026-04-01", amount: 22000, status: "Completed" as const, purpose1: "REVENUE" as const, purpose2: "Rent" as const, typeDetails: "Standard" as const, fromParty: "Amit Kumar", fromPartyType: "Tenant" as const, toParty: "Flent", toPartyType: "Platform" as const, paymentChannel: "NEFT" as const, paymentProvider: "IDFC" as const, gatewayRef: "pay_def789012", settlementRef: "UTR2345678901", createdBy: "System", authorisedBy: "—", contractUid: "TC-002", contactId: "TEN-002", pid: "PID-003", rid: "RID-003-A", merchantId: null, vendorCode: null, lineItemDesc: "Monthly Rent – Apr 2026" },
    { id: "TXN-20260405-00003", creditDebit: "Credit" as const, date: "2026-04-05", amount: 12000, status: "Pending" as const, purpose1: "REVENUE" as const, purpose2: "Rent" as const, typeDetails: "Standard" as const, fromParty: "Priya Singh", fromPartyType: "Tenant" as const, toParty: "Flent", toPartyType: "Platform" as const, paymentChannel: "Payment Link" as const, paymentProvider: "Razorpayx" as const, gatewayRef: "—", settlementRef: "—", createdBy: "System", authorisedBy: "—", contractUid: "TC-003", contactId: "TEN-003", pid: "PID-002", rid: "RID-002-A", merchantId: null, vendorCode: null, lineItemDesc: "Monthly Rent – Apr 2026" },
    { id: "TXN-20260401-00004", creditDebit: "Credit" as const, date: "2026-04-01", amount: 14000, status: "Completed" as const, purpose1: "REVENUE" as const, purpose2: "Rent" as const, typeDetails: "Standard" as const, fromParty: "Sanjay Patel", fromPartyType: "Tenant" as const, toParty: "Flent", toPartyType: "Platform" as const, paymentChannel: "Auto-debit (NACH)" as const, paymentProvider: "Kotak" as const, gatewayRef: "pay_ghi345678", settlementRef: "UTR3456789012", createdBy: "System", authorisedBy: "—", contractUid: "TC-004", contactId: "TEN-004", pid: "PID-006", rid: "RID-006-A", merchantId: null, vendorCode: null, lineItemDesc: "Monthly Rent – Apr 2026" },
    { id: "TXN-20260401-00005", creditDebit: "Credit" as const, date: "2026-04-01", amount: 15000, status: "Completed" as const, purpose1: "REVENUE" as const, purpose2: "Rent" as const, typeDetails: "Standard" as const, fromParty: "Neha Gupta", fromPartyType: "Tenant" as const, toParty: "Flent", toPartyType: "Platform" as const, paymentChannel: "UPI" as const, paymentProvider: "Razorpayx" as const, gatewayRef: "pay_jkl901234", settlementRef: "UTR4567890123", createdBy: "System", authorisedBy: "—", contractUid: "TC-005", contactId: "TEN-005", pid: "PID-005", rid: "RID-005-A", merchantId: null, vendorCode: null, lineItemDesc: "Monthly Rent – Apr 2026" },
    // Landlord payouts (Debit)
    { id: "TXN-20260405-00006", creditDebit: "Debit" as const, date: "2026-04-05", amount: 55000, status: "Completed" as const, purpose1: "COGS" as const, purpose2: "Rent" as const, typeDetails: "Standard" as const, fromParty: "Flent", fromPartyType: "Platform" as const, toParty: "Suresh Iyer", toPartyType: "Landlord" as const, paymentChannel: "NEFT" as const, paymentProvider: "Kotak" as const, gatewayRef: "—", settlementRef: "UTR5678901234", createdBy: "Srashti Jain", authorisedBy: "Admin", contractUid: null, contactId: null, pid: "PID-001", rid: null, merchantId: "MER-001", vendorCode: null, lineItemDesc: "Landlord Payout – Apr 2026 – Indiranagar Residency" },
    { id: "TXN-20260405-00007", creditDebit: "Debit" as const, date: "2026-04-05", amount: 90000, status: "Pending" as const, purpose1: "COGS" as const, purpose2: "Rent" as const, typeDetails: "Standard" as const, fromParty: "Flent", fromPartyType: "Platform" as const, toParty: "Meena Reddy", toPartyType: "Landlord" as const, paymentChannel: "NEFT" as const, paymentProvider: "Kotak" as const, gatewayRef: "—", settlementRef: "—", createdBy: "Srashti Jain", authorisedBy: "—", contractUid: null, contactId: null, pid: "PID-002", rid: null, merchantId: "MER-002", vendorCode: null, lineItemDesc: "Landlord Payout – Apr 2026 – Koramangala Heights" },
    // Vendor payment (Debit)
    { id: "TXN-20260408-00008", creditDebit: "Debit" as const, date: "2026-04-08", amount: 1200, status: "Completed" as const, purpose1: "OPEX" as const, purpose2: "Vendor" as const, typeDetails: "Standard" as const, fromParty: "Flent", fromPartyType: "Platform" as const, toParty: "AquaFix Plumbing", toPartyType: "Vendor" as const, paymentChannel: "UPI" as const, paymentProvider: "Razorpayx" as const, gatewayRef: "pay_mno567890", settlementRef: "UTR6789012345", createdBy: "Nisha Mehta", authorisedBy: "Srashti Jain", contractUid: null, contactId: null, pid: "PID-001", rid: "RID-001-A", merchantId: null, vendorCode: "VEN-001", lineItemDesc: "Plumbing repair – TKT-001" },
    // Security deposit (Credit)
    { id: "TXN-20260115-00009", creditDebit: "Credit" as const, date: "2026-01-15", amount: 36000, status: "Completed" as const, purpose1: "REVENUE" as const, purpose2: "Deposit" as const, typeDetails: "SDT" as const, fromParty: "Rahul Sharma", fromPartyType: "Tenant" as const, toParty: "Flent", toPartyType: "Platform" as const, paymentChannel: "NEFT" as const, paymentProvider: "IDFC" as const, gatewayRef: "pay_pqr123456", settlementRef: "UTR7890123456", createdBy: "System", authorisedBy: "—", contractUid: "TC-001", contactId: "TEN-001", pid: "PID-001", rid: "RID-001-A", merchantId: null, vendorCode: null, lineItemDesc: "Security Deposit – Rahul Sharma – Indiranagar" },
    // More rent collections
    { id: "TXN-20260401-00010", creditDebit: "Credit" as const, date: "2026-04-01", amount: 9500, status: "Completed" as const, purpose1: "REVENUE" as const, purpose2: "Rent" as const, typeDetails: "Standard" as const, fromParty: "Vikram Rao", fromPartyType: "Tenant" as const, toParty: "Flent", toPartyType: "Platform" as const, paymentChannel: "UPI" as const, paymentProvider: "Razorpayx" as const, gatewayRef: "pay_stu789012", settlementRef: "UTR8901234567", createdBy: "System", authorisedBy: "—", contractUid: "TC-006", contactId: "TEN-006", pid: "PID-004", rid: "RID-004-A", merchantId: null, vendorCode: null, lineItemDesc: "Monthly Rent – Apr 2026" },
    { id: "TXN-20260401-00011", creditDebit: "Credit" as const, date: "2026-04-01", amount: 25000, status: "Completed" as const, purpose1: "REVENUE" as const, purpose2: "Rent" as const, typeDetails: "Standard" as const, fromParty: "Ravi Prasad", fromPartyType: "Tenant" as const, toParty: "Flent", toPartyType: "Platform" as const, paymentChannel: "Auto-debit (NACH)" as const, paymentProvider: "Kotak" as const, gatewayRef: "pay_vwx345678", settlementRef: "UTR9012345678", createdBy: "System", authorisedBy: "—", contractUid: "TC-010", contactId: "TEN-010", pid: "PID-011", rid: "RID-011-A", merchantId: null, vendorCode: null, lineItemDesc: "Monthly Rent – Apr 2026" },
    { id: "TXN-20260403-00012", creditDebit: "Credit" as const, date: "2026-04-03", amount: 10000, status: "Failed" as const, purpose1: "REVENUE" as const, purpose2: "Rent" as const, typeDetails: "Standard" as const, fromParty: "Kavita Joshi", fromPartyType: "Tenant" as const, toParty: "Flent", toPartyType: "Platform" as const, paymentChannel: "Auto-debit (NACH)" as const, paymentProvider: "Kotak" as const, gatewayRef: "pay_fail001", settlementRef: "—", createdBy: "System", authorisedBy: "—", contractUid: "TC-009", contactId: "TEN-009", pid: "PID-007", rid: "RID-007-A", merchantId: null, vendorCode: null, lineItemDesc: "Monthly Rent – Apr 2026 (NACH failed)" },
];

// ─── OVERHEADS ──────────────────────────────────────────────────────────────

export const OVERHEADS = [
    { id: "OH-001", pid: "PID-001", pidName: "Indiranagar Residency", category: "Maintenance" as const, objectType: "Recurring" as const, frequency: "Monthly" as const, amount: 2500, cutoffDate: "5", paymentToLandlord: false, collectionFromTenant: true, startDate: "2025-06-15", endDate: "2027-06-14", nextDueDate: "2026-05-05" },
    { id: "OH-002", pid: "PID-001", pidName: "Indiranagar Residency", category: "WiFi" as const, objectType: "Recurring" as const, frequency: "Monthly" as const, amount: 1200, cutoffDate: "1", paymentToLandlord: false, collectionFromTenant: false, startDate: "2025-06-15", endDate: "2027-06-14", nextDueDate: "2026-05-01" },
    { id: "OH-003", pid: "PID-002", pidName: "Koramangala Heights", category: "Maintenance" as const, objectType: "Recurring" as const, frequency: "Monthly" as const, amount: 1800, cutoffDate: "1", paymentToLandlord: true, collectionFromTenant: true, startDate: "2025-05-20", endDate: "2027-05-19", nextDueDate: "2026-05-01" },
    { id: "OH-004", pid: "PID-002", pidName: "Koramangala Heights", category: "WiFi" as const, objectType: "Recurring" as const, frequency: "Monthly" as const, amount: 1500, cutoffDate: "1", paymentToLandlord: false, collectionFromTenant: false, startDate: "2025-05-20", endDate: "2027-05-19", nextDueDate: "2026-05-01" },
    { id: "OH-005", pid: "PID-003", pidName: "HSR Green Villas", category: "Maintenance" as const, objectType: "Recurring" as const, frequency: "Quarterly" as const, amount: 9000, cutoffDate: "5", paymentToLandlord: false, collectionFromTenant: true, startDate: "2025-07-01", endDate: "2027-06-30", nextDueDate: "2026-07-05" },
    { id: "OH-006", pid: "PID-003", pidName: "HSR Green Villas", category: "Electricity" as const, objectType: "Recurring" as const, frequency: "Monthly" as const, amount: 3500, cutoffDate: "15", paymentToLandlord: false, collectionFromTenant: true, startDate: "2025-07-01", endDate: "2027-06-30", nextDueDate: "2026-05-15" },
    { id: "OH-007", pid: "PID-005", pidName: "JP Nagar Palm Court", category: "Water" as const, objectType: "Recurring" as const, frequency: "Monthly" as const, amount: 500, cutoffDate: "10", paymentToLandlord: false, collectionFromTenant: false, startDate: "2025-04-15", endDate: "2027-04-14", nextDueDate: "2026-05-10" },
    { id: "OH-008", pid: "PID-008", pidName: "Banashankari Emerald", category: "Maintenance" as const, objectType: "One-Time" as const, frequency: "—" as const, amount: 15000, cutoffDate: "—", paymentToLandlord: false, collectionFromTenant: false, startDate: "2026-04-01", endDate: "2026-04-30", nextDueDate: "2026-04-30" },
];

// ─── VENDORS ────────────────────────────────────────────────────────────────

export const VENDORS = [
    { id: "VEN-001", name: "AquaFix Plumbing", vendorType: "Freelancer" as const, contactPerson: "Raju Kumar", phone: "+91 98111 22233", email: "raju@aquafix.in", city: "Bangalore", address: "45 Wilson Garden", gstNo: "29ABCDE1234F1Z5", panNo: "ABCDE1234F", specialization: "Plumbing & Water Systems", qualityTier: "T1" as const, standardisationFit: "C1" as const, tat: 2, paymentTerms: "Net 15", totalOrders: 24, totalSpend: "₹78,400", lastOrder: "Apr 8, 2026", status: "Active" as const, rating: 4.5 },
    { id: "VEN-002", name: "SparkElectric Co.", vendorType: "Aggregate" as const, contactPerson: "Sunil Reddy", phone: "+91 98222 33344", email: "sunil@sparkelectric.in", city: "Bangalore", address: "12 Residency Rd", gstNo: "29FGHIJ5678K2Z6", panNo: "FGHIJ5678K", specialization: "Electrical Repairs & Installations", qualityTier: "T1" as const, standardisationFit: "C2" as const, tat: 1, paymentTerms: "Net 7", totalOrders: 18, totalSpend: "₹52,200", lastOrder: "Apr 11, 2026", status: "Active" as const, rating: 4.8 },
    { id: "VEN-003", name: "WoodCraft Solutions", vendorType: "Retailer" as const, contactPerson: "Manoj Gowda", phone: "+91 98333 44455", email: "manoj@woodcraft.in", city: "Bangalore", address: "88 Peenya Industrial", gstNo: "29KLMNO9012P3Z7", panNo: "KLMNO9012P", specialization: "Carpentry & Furniture", qualityTier: "T2" as const, standardisationFit: "C1" as const, tat: 3, paymentTerms: "Net 30", totalOrders: 15, totalSpend: "₹1,45,000", lastOrder: "Mar 25, 2026", status: "Active" as const, rating: 4.2 },
    { id: "VEN-004", name: "HomeAppliance Hub", vendorType: "Distributor" as const, contactPerson: "Priya Nair", phone: "+91 98444 55566", email: "priya@homeappliance.in", city: "Bangalore", address: "34 Brigade Rd", gstNo: "29PQRST3456U4Z8", panNo: "PQRST3456U", specialization: "Appliance Repair & Replacement", qualityTier: "T1" as const, standardisationFit: "C2" as const, tat: 2, paymentTerms: "Net 15", totalOrders: 22, totalSpend: "₹2,10,000", lastOrder: "Apr 3, 2026", status: "Active" as const, rating: 4.6 },
    { id: "VEN-005", name: "CleanSweep Services", vendorType: "Freelancer" as const, contactPerson: "Lakshman P.", phone: "+91 98555 66677", email: "lakshman@cleansweep.in", city: "Bangalore", address: "67 Whitefield Main", gstNo: "29UVWXY7890Z5A9", panNo: "UVWXY7890Z", specialization: "Cleaning & Pest Control", qualityTier: "T2" as const, standardisationFit: "C3" as const, tat: 1, paymentTerms: "Immediate", totalOrders: 30, totalSpend: "₹45,000", lastOrder: "Apr 6, 2026", status: "Active" as const, rating: 4.0 },
    { id: "VEN-006", name: "PaintPro Interiors", vendorType: "Wholeseller" as const, contactPerson: "Deepak M.", phone: "+91 98666 77788", email: "deepak@paintpro.in", city: "Bangalore", address: "99 Jayanagar 4th Block", gstNo: "29BCDEF2345G6H0", panNo: "BCDEF2345G", specialization: "Painting & Interiors", qualityTier: "T3" as const, standardisationFit: "C2" as const, tat: 5, paymentTerms: "Net 30", totalOrders: 8, totalSpend: "₹92,000", lastOrder: "Feb 15, 2026", status: "Inactive" as const, rating: 3.5 },
];

// ─── FSINs ──────────────────────────────────────────────────────────────────

export const FSINS = [
    { id: "FSIN-BED-001", name: "Single Bed Frame – Metal", category: "Furniture" as const, type: "Moveable" as const, unitOfMeasure: "Unit", standardCost: "₹4,500", totalQuantity: 45, allocatedProperties: 8, hsnCode: "9403", description: "Standard metal single bed frame, powder coated", lastUpdated: "Mar 2026", vendorCode: "VEN-003", annualDepreciation: 15 },
    { id: "FSIN-MAT-001", name: "Single Mattress – 6\"", category: "Bedding" as const, type: "Moveable" as const, unitOfMeasure: "Unit", standardCost: "₹3,200", totalQuantity: 45, allocatedProperties: 8, hsnCode: "9404", description: "6-inch foam mattress, single size", lastUpdated: "Mar 2026", vendorCode: "VEN-003", annualDepreciation: 20 },
    { id: "FSIN-WRD-001", name: "2-Door Wardrobe – Engineered Wood", category: "Furniture" as const, type: "Static" as const, unitOfMeasure: "Unit", standardCost: "₹8,500", totalQuantity: 30, allocatedProperties: 7, hsnCode: "9403", description: "2-door wardrobe, engineered wood with laminate finish", lastUpdated: "Feb 2026", vendorCode: "VEN-003", annualDepreciation: 10 },
    { id: "FSIN-STD-001", name: "Study Table – Compact", category: "Furniture" as const, type: "Moveable" as const, unitOfMeasure: "Unit", standardCost: "₹3,800", totalQuantity: 35, allocatedProperties: 7, hsnCode: "9403", description: "Compact study table with drawer, engineered wood", lastUpdated: "Mar 2026", vendorCode: "VEN-003", annualDepreciation: 12 },
    { id: "FSIN-CHR-001", name: "Study Chair – Ergonomic", category: "Furniture" as const, type: "Moveable" as const, unitOfMeasure: "Unit", standardCost: "₹2,800", totalQuantity: 35, allocatedProperties: 7, hsnCode: "9401", description: "Ergonomic office chair with mesh back", lastUpdated: "Mar 2026", vendorCode: "VEN-004", annualDepreciation: 15 },
    { id: "FSIN-CUR-001", name: "Window Curtain Set", category: "Décor" as const, type: "Consumable" as const, unitOfMeasure: "Set", standardCost: "₹1,200", totalQuantity: 60, allocatedProperties: 9, hsnCode: "6303", description: "Blackout curtain set with rod and hooks", lastUpdated: "Jan 2026", vendorCode: "VEN-006", annualDepreciation: 25 },
    { id: "FSIN-GYS-001", name: "Instant Water Heater – 3L", category: "Appliance" as const, type: "Static" as const, unitOfMeasure: "Unit", standardCost: "₹3,500", totalQuantity: 20, allocatedProperties: 6, hsnCode: "8516", description: "3-litre instant water heater, ISI marked", lastUpdated: "Feb 2026", vendorCode: "VEN-004", annualDepreciation: 12 },
    { id: "FSIN-FAN-001", name: "Ceiling Fan – 1200mm", category: "Appliance" as const, type: "Static" as const, unitOfMeasure: "Unit", standardCost: "₹1,800", totalQuantity: 50, allocatedProperties: 10, hsnCode: "8414", description: "1200mm ceiling fan, 3-blade, white", lastUpdated: "Dec 2025", vendorCode: "VEN-002", annualDepreciation: 10 },
];

// ─── ITEMS ──────────────────────────────────────────────────────────────────

export const ITEMS = [
    { id: "ITEM-001", fsin: "FSIN-BED-001", name: "Single Bed Frame – Metal", type: "Moveable" as const, category: "Furniture", propertyId: "PID-001", propertyName: "Indiranagar Residency", rid: "RID-001-A", quantity: 1, unitCost: "₹4,500", condition: "Good" as const, vendor: "WoodCraft Solutions", lastAudit: "Mar 15, 2026", state: "PIB" as const, serialNo: "BED-001-001", location: "PID-001-RID-001-A" },
    { id: "ITEM-002", fsin: "FSIN-MAT-001", name: "Single Mattress – 6\"", type: "Moveable" as const, category: "Bedding", propertyId: "PID-001", propertyName: "Indiranagar Residency", rid: "RID-001-A", quantity: 1, unitCost: "₹3,200", condition: "Good" as const, vendor: "WoodCraft Solutions", lastAudit: "Mar 15, 2026", state: "PIB" as const, serialNo: "MAT-001-001", location: "PID-001-RID-001-A" },
    { id: "ITEM-003", fsin: "FSIN-WRD-001", name: "2-Door Wardrobe", type: "Static" as const, category: "Furniture", propertyId: "PID-001", propertyName: "Indiranagar Residency", rid: "RID-001-A", quantity: 1, unitCost: "₹8,500", condition: "Good" as const, vendor: "WoodCraft Solutions", lastAudit: "Mar 15, 2026", state: "PIB" as const, serialNo: "WRD-001-001", location: "PID-001-RID-001-A" },
    { id: "ITEM-004", fsin: "FSIN-STD-001", name: "Study Table – Compact", type: "Moveable" as const, category: "Furniture", propertyId: "PID-002", propertyName: "Koramangala Heights", rid: "RID-002-A", quantity: 1, unitCost: "₹3,800", condition: "Good" as const, vendor: "WoodCraft Solutions", lastAudit: "Feb 20, 2026", state: "PIB" as const, serialNo: "STD-002-001", location: "PID-002-RID-002-A" },
    { id: "ITEM-005", fsin: "FSIN-CHR-001", name: "Study Chair – Ergonomic", type: "Moveable" as const, category: "Furniture", propertyId: "PID-002", propertyName: "Koramangala Heights", rid: "RID-002-A", quantity: 1, unitCost: "₹2,800", condition: "Fair" as const, vendor: "HomeAppliance Hub", lastAudit: "Feb 20, 2026", state: "PIB" as const, serialNo: "CHR-002-001", location: "PID-002-RID-002-A" },
    { id: "ITEM-006", fsin: "FSIN-GYS-001", name: "Instant Water Heater – 3L", type: "Static" as const, category: "Appliance", propertyId: "PID-003", propertyName: "HSR Green Villas", rid: "RID-003-A", quantity: 1, unitCost: "₹3,500", condition: "Good" as const, vendor: "HomeAppliance Hub", lastAudit: "Mar 1, 2026", state: "PIB" as const, serialNo: "GYS-003-001", location: "PID-003-RID-003-A" },
    { id: "ITEM-007", fsin: "FSIN-FAN-001", name: "Ceiling Fan – 1200mm", type: "Static" as const, category: "Appliance", propertyId: "PID-003", propertyName: "HSR Green Villas", rid: "RID-003-A", quantity: 2, unitCost: "₹1,800", condition: "Good" as const, vendor: "SparkElectric Co.", lastAudit: "Mar 1, 2026", state: "PIB" as const, serialNo: "FAN-003-001", location: "PID-003-RID-003-A" },
    { id: "ITEM-008", fsin: "FSIN-CUR-001", name: "Window Curtain Set", type: "Consumable" as const, category: "Décor", propertyId: "PID-005", propertyName: "JP Nagar Palm Court", rid: "RID-005-A", quantity: 2, unitCost: "₹1,200", condition: "Good" as const, vendor: "PaintPro Interiors", lastAudit: "Jan 10, 2026", state: "PIB" as const, serialNo: "CUR-005-001", location: "PID-005-RID-005-A" },
    { id: "ITEM-009", fsin: "FSIN-BED-001", name: "Single Bed Frame – Metal", type: "Moveable" as const, category: "Furniture", propertyId: null, propertyName: "Warehouse", rid: null, quantity: 5, unitCost: "₹4,500", condition: "New" as const, vendor: "WoodCraft Solutions", lastAudit: "Apr 1, 2026", state: "WIB" as const, serialNo: "BED-WH-001", location: "WH01-R1" },
    { id: "ITEM-010", fsin: "FSIN-BED-001", name: "Single Bed Frame – Metal", type: "Moveable" as const, category: "Furniture", propertyId: null, propertyName: "Warehouse", rid: null, quantity: 1, unitCost: "₹4,500", condition: "Damaged" as const, vendor: "WoodCraft Solutions", lastAudit: "Apr 1, 2026", state: "DEAD" as const, serialNo: "BED-WH-002", location: "WH01-DEAD" },
];

// ─── NOTIFICATIONS ──────────────────────────────────────────────────────────

export const NOTIFICATIONS = [
    { id: "NTF-001", type: "SLA Breach" as const, message: "TKT-005 (Power socket) SLA breach in 2 hours — Urgent priority", timestamp: "2026-04-11 10:30", read: false, channel: "WhatsApp" as const, recipient: "Srashti Jain", status: "Delivered" as const },
    { id: "NTF-002", type: "Payment Failed" as const, message: "NACH auto-debit failed for Kavita Joshi (₹10,000) — TXN-20260403-00012", timestamp: "2026-04-03 09:15", read: true, channel: "Email" as const, recipient: "Finance Team", status: "Delivered" as const },
    { id: "NTF-003", type: "SLA Breach" as const, message: "TKT-004 (WiFi speed) approaching SLA limit — 6 hours remaining", timestamp: "2026-04-10 14:00", read: false, channel: "WhatsApp" as const, recipient: "CS Team", status: "Delivered" as const },
    { id: "NTF-004", type: "Item Lock" as const, message: "ITEM-009 (5× Single Bed Frame) locked >72h by PFS — review needed", timestamp: "2026-04-08 08:00", read: true, channel: "Email" as const, recipient: "Karthik Rajan", status: "Delivered" as const },
    { id: "NTF-005", type: "Rent Reminder" as const, message: "Rent due reminder sent to Priya Singh — ₹12,000 pending for Apr 2026", timestamp: "2026-04-04 09:00", read: true, channel: "WhatsApp" as const, recipient: "Priya Singh", status: "Delivered" as const },
    { id: "NTF-006", type: "Contract Expiry" as const, message: "TC-006 (Vikram Rao) expires in 90 days — renewal action required", timestamp: "2026-04-05 10:00", read: false, channel: "Email" as const, recipient: "Srashti Jain", status: "Delivered" as const },
    { id: "NTF-007", type: "Overhead Due" as const, message: "OH-005 (HSR Green Villas maintenance ₹9,000) quarterly payment due Jul 5", timestamp: "2026-04-10 08:00", read: true, channel: "Email" as const, recipient: "Nisha Mehta", status: "Delivered" as const },
];

// ─── INTERNAL USERS ─────────────────────────────────────────────────────────

export const USERS = [
    { id: "USR-001", name: "Srashti Jain", email: "srashti@flent.in", role: "Admin" as const, status: "Active" as const, lastLogin: "2026-04-11 09:15", assignedProperties: 6 },
    { id: "USR-002", name: "Nisha Mehta", email: "nisha@flent.in", role: "PSM" as const, status: "Active" as const, lastLogin: "2026-04-11 08:45", assignedProperties: 5 },
    { id: "USR-003", name: "Karthik Rajan", email: "karthik@flent.in", role: "PSM" as const, status: "Active" as const, lastLogin: "2026-04-10 17:30", assignedProperties: 4 },
    { id: "USR-004", name: "Riya Sharma", email: "riya@flent.in", role: "Sales" as const, status: "Active" as const, lastLogin: "2026-04-11 10:00", assignedProperties: 0 },
    { id: "USR-005", name: "Arjun Kapoor", email: "arjun.k@flent.in", role: "Finance" as const, status: "Active" as const, lastLogin: "2026-04-11 09:30", assignedProperties: 0 },
    { id: "USR-006", name: "Preet Kaur", email: "preet@flent.in", role: "Sales" as const, status: "Active" as const, lastLogin: "2026-04-09 16:00", assignedProperties: 0 },
    { id: "USR-007", name: "Manish Verma", email: "manish@flent.in", role: "Finance" as const, status: "Inactive" as const, lastLogin: "2026-03-15 11:00", assignedProperties: 0 },
];

// ─── INVENTORY SUMMARY (per-property) ───────────────────────────────────────

export const INVENTORY = PROPERTIES.filter(p => p.dealStage === "Under Contract").map(p => {
    const propItems = ITEMS.filter(i => i.propertyId === p.id);
    const moveableItems = propItems.filter(i => i.type === "Moveable").reduce((s, i) => s + i.quantity, 0);
    const staticItems = propItems.filter(i => i.type === "Static").reduce((s, i) => s + i.quantity, 0);
    const consumableItems = propItems.filter(i => i.type === "Consumable").reduce((s, i) => s + i.quantity, 0);
    const totalItems = moveableItems + staticItems + consumableItems;
    const totalValue = propItems.reduce((s, i) => s + i.quantity * parseInt(i.unitCost.replace(/[₹,]/g, "") || "0"), 0);
    return {
        propertyId: p.id,
        propertyName: p.name,
        totalItems,
        moveableItems,
        staticItems,
        consumableItems,
        totalValue: `₹${totalValue.toLocaleString()}`,
        lastAudit: propItems[0]?.lastAudit || "—",
        auditStatus: (totalItems > 0 ? "Completed" : "Pending") as "Completed" | "Pending" | "Overdue",
        discrepancies: p.id === "PID-002" ? 1 : 0,
    };
});

// ─── ANALYTICS (aggregated) ─────────────────────────────────────────────────

export const ANALYTICS = {
    totalRevenueYTD: "₹18,42,500",
    occupancyRate: 82,
    churnRate: 3.2,
    avgRevPerProperty: "₹1,67,500",
    tenantGrowth: [
        { month: "Nov", count: 62 }, { month: "Dec", count: 68 }, { month: "Jan", count: 74 },
        { month: "Feb", count: 79 }, { month: "Mar", count: 84 }, { month: "Apr", count: 88 },
    ],
    monthlyRevenue: [
        { month: "Nov", value: 285000 }, { month: "Dec", value: 295000 }, { month: "Jan", value: 310000 },
        { month: "Feb", value: 322000 }, { month: "Mar", value: 330000 }, { month: "Apr", value: 345000 },
    ],
};

export const OCCUPANCY = {
    totalUnits: PROPERTIES.reduce((s, p) => s + p.totalUnits, 0),
    occupiedUnits: PROPERTIES.reduce((s, p) => s + p.occupiedUnits, 0),
    vacantUnits: PROPERTIES.reduce((s, p) => s + (p.totalUnits - p.occupiedUnits), 0),
    occupancyPercentage: Math.round(
        (PROPERTIES.reduce((s, p) => s + p.occupiedUnits, 0) / PROPERTIES.reduce((s, p) => s + p.totalUnits, 0)) * 100
    ),
    perProperty: PROPERTIES.filter(p => p.dealStage === "Under Contract").map(p => ({
        name: p.name, total: p.totalUnits, occupied: p.occupiedUnits,
        rate: p.totalUnits > 0 ? Math.round((p.occupiedUnits / p.totalUnits) * 100) : 0,
    })),
};

export const REVENUE = {
    totalRevenue: "₹3,45,000",
    collectedAmount: "₹3,08,000",
    pendingAmount: "₹37,000",
    monthlyBreakdown: [
        { month: "Jan", collected: 280000, pending: 15000 },
        { month: "Feb", collected: 295000, pending: 22000 },
        { month: "Mar", collected: 310000, pending: 20000 },
        { month: "Apr", collected: 308000, pending: 37000 },
    ],
};

// ─── SETTINGS ───────────────────────────────────────────────────────────────

export const SETTINGS = {
    companyName: "Flent Housing Pvt. Ltd.",
    timezone: "Asia/Kolkata (IST)",
    currency: "INR (₹)",
    dateFormat: "DD/MM/YYYY",
    notifications: { email: true, sms: false, push: true },
    team: USERS,
    slaTargets: { low: 72, medium: 48, high: 24, urgent: 4 },
    dualControlThreshold: 10000,
};

// Legacy exports for backward compatibility
export const PAYMENTS = TRANSACTIONS.filter(t => t.creditDebit === "Credit" && t.purpose2 === "Rent").map(t => ({
    id: t.id, tenantId: t.contactId || "", tenantName: t.fromParty, rentalId: t.contractUid || "", propertyName: PROPERTIES.find(p => p.id === t.pid)?.name || "—", amount: `₹${t.amount.toLocaleString()}`, type: "Rent" as const, status: (t.status === "Completed" ? "Paid" : t.status === "Failed" ? "Overdue" : "Pending") as "Paid" | "Pending" | "Overdue", method: t.paymentChannel, date: t.date, upiId: "—", bankName: "—", invoiceNo: `INV-${t.id.slice(-5)}`, receiptNo: t.status === "Completed" ? `RCP-${t.id.slice(-5)}` : "—", purpose: t.lineItemDesc,
}));

export const RENTALS = TENANT_CONTRACTS.filter(tc => tc.status === "Active").map(tc => ({
    id: tc.id, tenantId: tc.tenantId, tenantName: tc.tenantName, propertyId: tc.pid, propertyName: tc.pidName, rentAmount: `₹${tc.totalRetailRent.toLocaleString()}`, moveInDate: tc.startDate, status: "Active" as const, contractStart: tc.startDate, contractEnd: tc.endDate, lockInMonths: tc.lockIn, licenseFee: `₹${tc.monthlyLicenseFee.toLocaleString()}`, gst: `₹${tc.gst}`, securityDeposit: `₹${tc.securityDeposit.toLocaleString()}`, escalation: "5% annual", noticePeriod: `${tc.noticePeriod} month${tc.noticePeriod > 1 ? "s" : ""}`,
}));

export const PROJECTS = [
    { id: "proj-01", name: "Sarjapur Road Onboarding", propertyCount: 1, status: "Planning" as const, description: "Onboard PID-012 with full furnishing and tenant readiness.", assignee: "Srashti Jain", priority: "High" as const, dueDate: "May 15, 2026" },
    { id: "proj-02", name: "Hennur Gardens Setup", propertyCount: 1, status: "Planning" as const, description: "Convert PID-013 from lead to active — furnish and prepare.", assignee: "Nisha Mehta", priority: "Medium" as const, dueDate: "Jun 1, 2026" },
    { id: "proj-03", name: "Q2 Inventory Audit", propertyCount: 11, status: "Active" as const, description: "Complete ICQA audit across all active properties.", assignee: "Karthik Rajan", priority: "High" as const, dueDate: "Apr 30, 2026" },
    { id: "proj-04", name: "Koramangala AC Upgrade", propertyCount: 1, status: "Completed" as const, description: "Replace window ACs with split units in PID-002.", assignee: "Karthik Rajan", priority: "Low" as const, dueDate: "Mar 31, 2026" },
];

export const ACTIVITIES = [
    { id: "act-01", type: "Payment" as const, description: "Rent received from Rahul Sharma – ₹18,000", date: "Apr 1, 2026", icon: "payment" },
    { id: "act-02", type: "Ticket" as const, description: "New ticket TKT-005 – Power socket not working (Urgent)", date: "Apr 11, 2026", icon: "ticket" },
    { id: "act-03", type: "Contract" as const, description: "Contract TC-011 signed – Sneha Kulkarni at Indiranagar", date: "Feb 20, 2026", icon: "contract" },
    { id: "act-04", type: "Move-in" as const, description: "Arjun Nair moved into Yelahanka Cedar Homes – RID-010-A", date: "Mar 10, 2026", icon: "movein" },
    { id: "act-05", type: "Payment" as const, description: "NACH failed for Kavita Joshi – ₹10,000", date: "Apr 3, 2026", icon: "alert" },
];

export const ALERTS = [
    { id: "alt-01", severity: "error" as const, message: "SLA breach imminent: TKT-005 (Urgent) — 2 hours remaining", date: "Apr 11, 2026" },
    { id: "alt-02", severity: "warning" as const, message: "Rent pending: Priya Singh ₹12,000 overdue by 6 days", date: "Apr 11, 2026" },
    { id: "alt-03", severity: "warning" as const, message: "Landlord payout pending: Meena Reddy ₹90,000 — Koramangala Heights", date: "Apr 11, 2026" },
    { id: "alt-04", severity: "info" as const, message: "Contract TC-006 (Vikram Rao) expires in 84 days — renewal required", date: "Apr 11, 2026" },
    { id: "alt-05", severity: "error" as const, message: "NACH auto-debit failed: Kavita Joshi ₹10,000 — manual collection needed", date: "Apr 3, 2026" },
];
